### ISSUE TITLE
windows: fix WAL lock

### ISSUE THREAD

**Issue by philips** [coreos/etcd#1972]
@chai2010 said there is a windows file locker (not include TryLock):
https://code.google.com/p/leveldb-go/source/browse/leveldb/db/file_lock_windows.go

We need someone to write, test and maintain the lock code for Windows. Right now it is a no-op in pkg/fileutil/lock_windows.go.

/cc @AndyPook @rwindelz @chai2010 @fceller

**Comment by fceller** [comment]
The code in 
https://code.google.com/p/leveldb-go/source/browse/leveldb/db/file_lock_windows.go
indeed works. The default "share" mode for CreateFile is "share nothing". Therefore the file is locked by default when created.

**Comment by xiang90** [comment]
@fceller Kindly ping. Are you still interested in working on this one?

**Comment by fceller** [comment]
Unfortunately we are focused on Linux at the moment. Therefore I'm afraid I cannot at work on this in the next months - as much as I would like to do it.

**Comment by AdoHe** [comment]
@xiang90 @fceller I did some simple test, it indeed works.

**Comment by gyuho** [comment]
I think related Windows code is not open, so it seems hard to implement the `fileutil.Lock` interface correctly:

- [`LockFile`](https://msdn.microsoft.com/en-us/library/windows/desktop/aa363778(v=vs.85).aspx) is open, and there are many Go implementation of [this](https://github.com/tgulacsi/lock/blob/master/lock_windows.go).
- [`UnlockFile`](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365715(v=vs.85).aspx) source code is not open. And there's no implementation of this in other languages either.

**Comment by heyitsanthony** [comment]
@gyuho we could probably roll our own `UnlockFile`; it's just a system call...

**Comment by gyuho** [comment]
@heyitsanthony Ok, I will research more about syscall flags. Thanks!

**Comment by gyuho** [comment]
https://github.com/coreos/etcd/pull/4719 has flock implementation in Windows. I believe the implementation is correct, but because of the way we use `flock` in other OSes, it won't work when it's used with other packages:

1. Opening a file in Windows locks the file exclusively to the file descriptor that it opened with. Even with the `syscall.FILE_SHARE_READ|syscall.FILE_SHARE_WRITE` flags, the file access cannot be shared with other functions. Please see the second answer http://stackoverflow.com/questions/3560651/whats-the-least-invasive-way-to-read-a-locked-file-in-c-sharp-perhaps-in-unsaf.
2. `fileutil.NewLock` acquires the lock, but it can only be deleted by outside functions. Any function trying to read or write without `fileutil.NewLock` will fail. Which means `wal` package is not going to work.

So *I think*, without changing the whole interface of `pkg/fileutil` and `wal`, flock won't work in windows. 

And there are other disadvantages in running Windows, like boltdb options https://github.com/coreos/etcd/blob/master/storage/backend/boltoption_windows.go. Both are important features but missing in windows platform. 

We should explain this in `README` or print out warning messages when building.

Any thoughts? /cc @xiang90 @heyitsanthony 

Thanks.

**Comment by heyitsanthony** [comment]
It looks like the `Lock` stuff needs to be refactored anyway (e.g., the same interface is copied across the per-platform files-- yuck). Only WAL seems to use it, so I don't think it'd be too disruptive to change the way flocks are exposed. I was thinking something like:
```
type Lock interface {
// Name gives the name of the file for locking
Name() string
// TryLock attempts to open a file with exclusive access; fails if already locked.
TryLock() (*os.File, error)
// Lock opens a file with exclusive access
Lock() (*os.File, error)
// Unlock releases the lock and closes the associated file
Unlock() error
}
```

**Comment by gyuho** [comment]
@heyitsanthony Thanks! I will try that.

**Comment by gyuho** [comment]
Closing via https://github.com/coreos/etcd/pull/4871.
