### ISSUE TITLE
Support SPDY / HTTP2

### ISSUE THREAD

**Issue by jurmous** [coreos/etcd#1980]
SPDY and soon HTTP2 would allow to create 1 persistent connection in which each request and response get an id with "X-SPDY-Stream-ID" header so they can be handled async on that 1 connection. 

This would allow for much more efficient etcd clients. Also TLS handshakes would only be done once on connection creation.

**Comment by xiang90** [comment]
@jurmous @philips We probably will go with grpc for v3, which utilize HTTP2 features.

**Comment by philips** [comment]
@xiang90 We can consider giving access to v2 over HTTP2 too, right?

**Comment by rektide** [comment]
Etcd v2 is a model citizen of how to expose resources on the web because it has such a great, simple and elegant general purpose API that anyone with a rest-client can easily begin to use against HTTP: I'd love to see the transport upgraded, while still keeping the blissful resourceful v2 API largely intact.

I do think there's room to explore using http2/push to enhance the wait capabilities: #2844.

**Comment by xiang90** [comment]
If we build etcd with go 1.6 and enable HTTPs, everything will be HTTP2 (client needs to support HTTP2 too). Also v3 API is already http2 right now.
