### ISSUE TITLE
Auto-increment watch index?

### ISSUE THREAD

**Issue by lavalamp** [coreos/etcd#2047]
Supose client Alice watches /key1 at index 5, and then 1000 unrelated changes happen to /key2. As I understand it, Alice will get a 401 window expired error.

I have not looked at etcd's code, so maybe this question is hopelessly naive. But I wonder if it would be possible for etcd to increment the watch's index for every unrelated change it sees. That is, the code that checks "Did this watch at index 5 fire?" when it sees change 6, should increment the 5 to a 6. This would allow clients to re-get and re-watch much less often.

Clients of course have to be able to re-get and re-watch to be correct, but minimizing how often they have to do it seems important.

(Original inspiration: https://github.com/GoogleCloudPlatform/kubernetes/pull/3235)

**Comment by xiang90** [comment]
@lavalamp 
If I understand the problem correctly, that requires etcd to:
1. know the identification of each watcher. so that when the watcher comes back, etcd can recover its state.

2. keep the watcher for some time interval even if the connection is closed with the hope that the watcher will come back.

That complicates the server, since it pushes the recovery logic to the server side. Also the client still need to prepare for the same failure (we cannot wait for the watcher coming back for unlimited amount of time).

So my question is: are you trying to simplify the client logic? or trying to make the recovery more efficient by pushing some state to the server side?

**Comment by xiang90** [comment]
@lavalamp Also please note
>Supose client Alice watches /key1 at index 5, and then 1000 unrelated changes happen to /key2. As I understand it, Alice will get a 401 window expired error.

This will not trigger a 401. Only when you do the re-watch at index 5, there will be a 401.

**Comment by lavalamp** [comment]
@xiang90 Thank you, I think this is my misunderstanding of how the watch mechanism worked.

I see now that the watch is closed and a new one is opened when an event happens. I didn't realize that because the client we use hides this detail by re-watching for us.

Is there a reason why the watch is ended after the first result? Why not keep the HTTP channel open and keep sending results until the client closes the HTTP connection?

**Comment by xiang90** [comment]
@lavalamp Actually etcd supports streaming watch, but the go-etcd client does not support it right now. But i think it is not normal to see the out of window error for an instant re-watch (). Probably, the receiver of the watcher blocks for a long time?

**Comment by xiang90** [comment]
@lavalamp @smarterclayton closed in favor of https://github.com/coreos/etcd/issues/2048
