### ISSUE TITLE
Super unclear config

### ISSUE THREAD

**Issue by analytically** [coreos/etcd#2163]
2015/01/27 16:05:49 etcd: listening for peers on http://0.0.0.0:2380
2015/01/27 16:05:49 etcd: listening for client requests on http://0.0.0.0:2379
2015/01/27 16:05:49 etcd: stopping listening for client requests on http://0.0.0.0:2379
2015/01/27 16:05:49 etcd: stopping listening for peers on http://0.0.0.0:2380
2015/01/27 16:05:49 etcd: default has different advertised URLs in the cluster and advertised peer URLs list

**Comment by xiang90** [comment]
@analytically 
Can you please make your issue more clear? 

Do you mean the default configuration is not clear? Or the printed configuration is not clear? 
Or the error message is not clear?

**Comment by analytically** [comment]
I had a hard time figuring out what all those different messages mean. But I got it working.

**Comment by joestein** [comment]
@analytically what did you do to get it working?

**Comment by yichengq** [comment]
@joestein You need to set `--initial-cluster` if you change its name or peer address.

**Comment by joestein** [comment]
Yeah there were a few things I needed this is what ended up working on two machines for me

{code}

./etcd -proxy on -name infra0 -initial-advertise-peer-urls http://ipOne:2380 \
  -listen-peer-urls http://ipOne:2380 \
  -initial-cluster-token etcd-cluster-1 \
  -initial-cluster infra0=http://ipOne:2380,infra1=http://ipTwo:2380 \
  -initial-cluster-state new \
  -initial-advertise-peer-urls 'http://ipOne:2380,http://ipTwo:2380' \
  -advertise-client-urls 'http://ipOne:2379,http://ipTwo:2379' \
  -listen-client-urls http://ipOne:2379

./etcd -proxy on -name infra1 -initial-advertise-peer-urls http://ipTwo:2380 \
  -listen-peer-urls http://ipTwo:2380 \
  -initial-cluster-token etcd-cluster-1 \
  -initial-cluster infra0=http://ipOne:2380,infra1=http://ipTwo:2380 \
  -initial-cluster-state new  \
  -initial-advertise-peer-urls 'http://ipOne:2380,http://ipTwo:2380' \
  -advertise-client-urls 'http://ipOne:2379,http://ipTwo:2379' \
  -listen-client-urls http://ipTwo:2379

{code}

where ipOne and ipTwo are the host for the two machines respectively (since ports would conflict)

**Comment by yichengq** [comment]
A good example to start is at https://github.com/coreos/etcd/blob/master/Procfile
