### ISSUE TITLE
Automatically sync cluster members

### ISSUE THREAD

**Issue by bcwaldon** [coreos/etcd#2255]
As of https://github.com/coreos/etcd/commit/7d172bb1142eee5ee3bb6b2b4f08e2390217e01f, etcd/client.Client must sync the current member list manually (via Client.Sync). This behavior should happen automatically, but be configurable manually through etcd/client.ClientConfig (NoAutosync field that defaults to false). There are two events that should trigger a sync:
1. time (every 10min, for example)
2. endpoint becomes unhealthy (see https://github.com/coreos/etcd/issues/2254)

**Comment by fabxc** [comment]
I'm wondering if the config should default differently, i.e., `cfg.Autosync = false`.
With a running background sync the client needs some Close method. The API constructors make it kind of easy to return the API and forget about the client which seems fine for short-living clients (command/members_command.go is a good example.) But it's also easy to forget to set `NoAutosync = true` in those cases.

Explicitly activating autosync could be a good reminder to close properly.

**Comment by yichengq** [comment]
@xiang90 @bcwaldon @fabxc 

i have some thoughts about this feature:
1. maybe it is not a good time to do sync when `endpoint becomes unhealthy`. My understanding is that the sync is to catch up the possible change of endpoints. I don't expect users to remove all old machines in a short time, so waiting for some time to sync is fine. In the future, client should watch on endpoint change, and that will not be a problem then.
2. I don't think it is good to set AutoSync a config option. It is weird for a client logic to run some background goroutine. I would suggest an explicit `KeepSync` func that will run forever, and users could go this function if he wants. The function can have a context parameter to let user terminate it.
3. `KeepSync` could be set as a package function instead of a member function to make Client interface as simple as possible.

**Comment by yichengq** [comment]
The original issue wants to add `AutoSync` field, but I don't think it is a good idea. `AutoSync = true` will introduce a goroutine to sync periodically in background, which makes struct not easily controllable.

But providing users a recommended way to catch up the change of cluster is valuable, so it is good to add a function to handle this. I don't use `automatic` word because it indicates operating without external control, but it is not true here because user needs to call the function anyway.
