### ISSUE TITLE
Move discovery service client into client pkg

### ISSUE THREAD

**Issue by bcwaldon** [coreos/etcd#2256]
As of https://github.com/coreos/etcd/commit/7d172bb1142eee5ee3bb6b2b4f08e2390217e01f, there exists a client in the etcd/discovery pkg that wraps a etcd/client.Client and adds logic specifically for interacting with an etcd discovery service. This separation dictates that etcd/client maintain a etcd/client.NewKeysAPIWithPrefix constructor. Ideally, NewKeysAPIWithPrefix would not exist, and the client logic in the etcd/discovery pkg moves to etcd/client. It could look something like this:

```
func NewDiscoveryService() DiscoveryService {
    return &httpDiscoveryService{
        ...
    }
}

type DiscoveryConfig struct {
    Size int
}

type DiscoveryService interface {
    Join(peerURL string, cfg DiscoveryConfig) (string, error)
    Members() ([]Member, error)
}
```

**Comment by yichengq** [comment]
Based on xiang's opinions and my experiences on code change, I think there is no need to move discovery service client into client pkg today. Here are reasons:
1. joinCluster logic could only be used when discovery, so it is fine to leave it at /discovery.
2. the cluster info saved in discovery service is only valid at bootstrap stage, and users could get cluster info from etcd store after bootstrapping. getCluster logic is only used when discovery, so it is fine to leave it at /discovery.
3. discovery service client includes lots of valuable log and error which is specific for itself. Moving the client into /client turns out to be moving the whole file and introducing complicated log interface into client pkg.

**Comment by xiang90** [comment]
Closing
