### ISSUE TITLE
configuration file option to enable/disable the possibility to remotely shutdown etcd

### ISSUE THREAD

**Issue by grimnight** [coreos/etcd#2395]
Can you add configuration file option to enable/disable the possibility to remotely shutdown etcd?

**Comment by kelseyhightower** [comment]
@grimnight It seems this request is driven by the fact that etcd is being started outside of a process manager like upstart or systemd, so there is nothing to capture the "configuration" flags used to start etcd. If etcd is restarted there is no way to know how it was started originally because of the lack of configuration file.

Currently etcd does not have a config file because most configuration values cannot be changed between restarts; the cluster configuration is stored in the etcd data directory after the first run. It would also cause problems if you were to change cluster setting to join a different cluster with an existing data directory.

The same etcd data directory must be reused between restarts, but it maybe possible to use the default data dir location to get the desired behavior. I'm going to test this out and see if it works.

**Comment by kelseyhightower** [comment]
@grimnight There are currently no plans to add a configuration file to etcd. Once the etcd core matures a little more, such as adding the new backend store and other features that might require tuning, we might revisit this. For now etcd does not have a configuration file.
