### ISSUE TITLE
disk io with etcd and issue with snapshot flag.

### ISSUE THREAD

**Issue by anilmoris** [coreos/etcd#2409]
I am seeing high disk io with etcd. I am using v2. 
while attempting to run it with snapshot false. I am seeing this 
flag "-snapshot" is no longer supported

I tried ETCD_SNAPSHOT=false; export ETCD_SNAPSHOT as well but keep getting flag "-snapshot" is no longer supported and I see high disk io from etcd in iotop.

How can I force etcd use only memory and not touch disk. I have 100's of servers trying to update to dht etcd cluster. every 4 seconds.

Thanks,

**Comment by kelseyhightower** [comment]
@anilmoris Yes, the snapshot flag is no longer available in etcd v2.0.x, you'll have to tune snapshots using the `--snapshot-count` flag. By default etcd will create a snapshot every 10000 transactions. Try bumping this to say 100000.

We are working to add more tuning, but since etcd is currently backed by an in memory store snapshots are critical for normal operation. We do mitigate data loss with a WAL file, but to limit memory usage we use snapshots.

That's what you can do right now to reduce the number of snapshots. 

I do have a few questions regarding your hardware setup and etcd deployment in general. What kind of disks are the etcd data dirs running on? I found that basic cloud disks are really slow, I mean really slow. We tend to use local SSDs on our cloud instances to help deal with the current etcd snapshots (we are working to fix this soon).

**Comment by xiang90** [comment]
@anilmoris I think the root problem is etcd does not batch `fsync`s in 2.0 release. Each entry it writes to its write ahead log requires a `fsync`. We plan to do it in the laster release to reduce the pressure on the local disk and improve the write throughput. 

https://github.com/coreos/etcd/issues/1757

**Comment by anilmoris** [comment]
Thanks for the response, I am using enterprise high speed SSD locally on the box where etcd is running.
I will increase --snapshot-count and try this.

I was planning to use tmpfs as data dir for etcd, but I could not figure out a max size I can use reliably.
Do you have any suggestions, concerns on using tmpfs?  I can allocate 2 to 3 GB if that is ever going to be the max size of the data directory.

**Comment by xiang90** [comment]
@anilmoris It depends on your data put into etcd. etcd will clean up old wal files and snapshot files.

**Comment by anilmoris** [comment]
I have 5 member cluster I see more writes  (disk I/O) when  all 5 box are up. 
with 3 member cluster same load/data I see much lower disk I/O.

If I go with a 9 member cluster, then each write is going to be written to all other 8 member's as well?

**Comment by kelseyhightower** [comment]
@anilmoris You have 5 nodes and 5 different servers? Are there any other work loads on the etcd database boxes?

**Comment by anilmoris** [comment]
let me clarify our setup.
I have a 5 machine etcd cluster.

I have around 100 server's doing writes to the above 5 machine etcd cluster.

I would like to know if one of the server does a  write to etcd cluster then is that write going to propagate to all the 5  machine in etcd cluster?

If yes then can I limit this, say in my 5 machine etcd cluster I want to keep only 3 copies, so when a write happens instead of propagating to all 5 machines in the cluster it should propagate to only 3 machines in the cluster.

**Comment by xiang90** [comment]
> I would like to know if one of the server does a write to etcd cluster then is that write going to propagate to all the 5 machine in etcd cluster?

Yes. etcd is a replicated log system. all servers will get a full copy of the same committed log.

**Comment by xiang90** [comment]
@anilmoris It seems that you have got the answer. Thanks for the question! 
I am closing this now. Feel free to reopen this or create another issue if you have any thing to follow up.
