### ISSUE TITLE
raft: introduce progress states

### ISSUE THREAD

**Issue by yichengq** [coreos/etcd#2501]
driven from #2497 

This is the state machine of progress. It adjusts the speed to replicate in different situations.

![graph](https://rawgit.com/yichengq/693908a5a69dea848d12/raw/b4a2811dd9a23aa644bbf671a6697f1e22740796/gistfile1.svg)

TODO:

- [ ] state machine
- [ ] flow control

/cc @bdarnell

**Comment by bdarnell** [comment]
Should we perhaps model this as a flow control problem instead of a state machine? I.e. send in "optimistic" mode whenever `next - match < N`. This can help with links that are slow but reliable (so there are no rejections to push back into "normal" mode), and avoids sending very large append batches when a node comes back online.
