### ISSUE TITLE
Etcd caused lots of TCP TIME_WAIT 

### ISSUE THREAD

**Issue by snowdreamist** [coreos/etcd#2513]
HI, all

I'm running a 5-node etcd cluster for days, and I found thousands of TCP TIME_WAIT that is caused by etcd.

Here's a piece of log by `netstat -ntp`

    tcp        0      0 192.168.150.16:40634    192.168.150.11:7001     TIME_WAIT   -               
    tcp        0      0 192.168.150.16:40858    192.168.150.11:7001     TIME_WAIT   -               
    tcp        0      0 192.168.150.16:40531    192.168.150.11:7001     TIME_WAIT   -               
    tcp        0      0 192.168.150.16:39757    192.168.150.11:7001     TIME_WAIT   -               
    tcp        0      0 192.168.150.16:40260    192.168.150.11:7001     TIME_WAIT   -               
    tcp        0      0 192.168.150.16:39680    192.168.150.11:7001     TIME_WAIT   -               
    tcp        0      0 192.168.150.16:39900    192.168.150.11:7001     TIME_WAIT   -               
    tcp        0      0 192.168.150.16:41071    192.168.150.11:7001     TIME_WAIT   -               
    tcp        0      0 192.168.150.16:39861    192.168.150.11:7001     TIME_WAIT   -               
    tcp        0      0 192.168.150.16:39806    192.168.150.11:7001     TIME_WAIT   -               
    tcp        0      0 192.168.150.16:40132    192.168.150.11:7001     TIME_WAIT   -               

This kind of records could be more than 1 thousand.

I know I can change the system config to reuse the time_wait state socket or make them fast recycled but I think there may exist a bug which caused this issus in etcd, hmm~ if some connections are not gracefully closed ?

**Comment by xiang90** [comment]
@snowdreamist `Time-wait` does not indicate the socket is not closed gracefully. I guess you are running etcd 2.0.5, which does not reuse any tcp connections. In 2.0.5, we kind of disable the HTTP keep alive, which causes a lot of TCP connection creations and closes.

We have fixed this issue in current master by not creating a lot of tcp connections. Can you give it a try? Or you can wait for the 2.1 release. Thanks for reporting!

**Comment by marc-barry** [comment]
@snowdreamist As @xiang90 stated this doesn't necessarily indicate a bug with `etcd`. The `TIME-WAIT ` state transition of a TCP connection is normal. If you look at figure 6 in [RFC793](http://tools.ietf.org/html/rfc793) it shows the valid state transitions of a TCP connection. The kicker with the `TIME-WAIT` state is that connections stay in this state for a relatively long period of time (i.e. a maximum of 4 minutes). So in the case of etcd 2.0.5 it isn't reusing TCP connections and so at steady state you'll end up with quite a few in connections in the `TIME-WAIT` state.

BTW, if you are on Linux and want to see the total number of connections in `TIME-WAIT` you can look in `/proc/net/sockstat`. It looks like this:
```
sockets: used 354
TCP: inuse 27 orphan 0 tw 23 alloc 86 mem 13
UDP: inuse 13 mem 4
UDPLITE: inuse 0
RAW: inuse 0
FRAG: inuse 0 memory 0
```

The value beside `tw` is the number in `TIME-WAIT`. It is also available in `/proc/net/netstat` under `TW`. But it is a bit harder to read.

**Comment by hookenz** [comment]
One reason you get lots of TIME_WAIT connections is because the client isn't initiating the close, the server is.  If the client isn't using a fixed port number then set SO_LINGER to zero and initiate shutdown call on write.  That should flush the buffer.  You can then close and you'll get rid of a lot of connections in TIME_WAIT.  It's called an abortive close and is quite useful in some cases.  Especially where servers get hammered with high numbers of connections in a short time.  I've found it actually works well and never had an issue with it or lost data.  I assume this connection stuff is part of the raft library?  Might take a look and see how it handles the connections.

**Comment by hookenz** [comment]
In etcd 0.46 it's actually a huge problem.  I'm seeing fresh 3 peer etcd servers on CoreOS bare metal (that aren't using the discovery URL) actually run out of file handles within a few days.  The etcd server becomes unresponsive and it corrupts it's data files.  The fix, clear out the etcd data on each server and restart.  
Otherwise, ensure you have unlimited file handles set, don't use the default.

For me, that's a show stopper and makes it unusable for production.  I guess it's not called 0.46 for nothing.  But then it's in a release claimed to be "stable"... so I dunno.  The fixes need to be back ported.

**Comment by yichengq** [comment]
@hookenz etcd 0.4.6 is not a stable one. Feel free to give etcd 2.0 a try.

**Comment by hookenz** [comment]
If 2.0 is stable why is it not in the alpha channel for CoreOS yet.  Any idea of release?
What's the best way to try etcd2, run it in docker?

**Comment by yichengq** [comment]
@hookenz We are struggling with upgrade path these days, and it will be out in a few weeks, if not sooner.
Either run it in docker or run it on the system is fine.

**Comment by yichengq** [comment]
Thanks for answers from @xiang90 and @marc-barry !

BTW, etcd 2.0 is released in CoreOS alpha channel now.

**Comment by zz** [comment]
I also have many connections on 2.0.10
```
core@prod-core01 ~ $ cat /proc/net/sockstat
sockets: used 1833
TCP: inuse 11 orphan 5 tw 2125 alloc 90 mem 11
UDP: inuse 2 mem 2
UDPLITE: inuse 0
RAW: inuse 0
FRAG: inuse 0 memory 0
```
```
core@prod-core01 ~ $ cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=681.2.0
VERSION_ID=681.2.0
BUILD_ID=
PRETTY_NAME="CoreOS 681.2.0"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

**Comment by hookenz** [comment]
@zz - make sure you're using etcd2.  It solves it for me.  If you use cloud-init use etc2 in place of etcd2 otherwise you'll be running etcd 0.4x

**Comment by zz** [comment]
@hookenz thanks, just upgrade to etcd2
