### ISSUE TITLE
Proxy round-robin/randomize connections to cluster

### ISSUE THREAD

**Issue by durzo** [coreos/etcd#2549]
We plan on having a fairly high QPS cluster, but currently all proxies connect to a single member of the cluster (it seems to be the first member returned by the service discovery url?) and only move on if that member becomes unavailable.

In our tests, this means the maximum rate of queries is dependent on the network throughput of a single cluster member, regardless of how many members we have.

Would it be possible to round-robin connections or even randomize them to spread the query load from proxies onto all cluster members? Correct me if I am wrong, but I believe reads can happen anywhere and writes are automatically redirected to the elected cluster leader.

**Comment by yichengq** [comment]
Yes, that is the case nowadays. The etcd client always targets on the first
endpoint for each request:
https://github.com/coreos/etcd/blob/master/client/client.go#L200
And it needs to be improved.

The further thought is to let client stick on one endpoint until it becomes
unavailable.

Could you file an issue for it?

Yicheng

**Comment by andrewnicols** [comment]
+1 to this. But I think that the stickiness needs to be slightly different.

Ideally the client should be sticky until either:
* the endpoint goes away; OR
* an endpoint is added.

Without this second point, if all but one endpoint goes away, all clients will point to the remaining endpoint. When the original endpoints come back or are replaced, the load will still be directed to the same individual server.

Ideally clients should select a new endpoint in an effort to rebalance when they start.

Additionally, endpoints could be chosen with source hashing (much like haproxy does) rather than entirely randomly. The client address will never change, and we know the number of available members. Producing a static mapping should also lead to a reasonably balanced endpoint selection in most environments.

**Comment by yichengq** [comment]
Randomize is done at https://github.com/coreos/etcd/pull/2637/files.
It shuffle endpoints to avoid being "stuck" to a single cluster member.

@andrewnicols We do have the issue to track more intelligent on choosing endpoint: https://github.com/coreos/etcd/issues/2254. Let us talk about it at that issue.

**Comment by durzo** [comment]
Thanks @yichengq will this patch be included in 2.0.10 ?

**Comment by yichengq** [comment]
Yes. :)

**Comment by yichengq** [comment]
link it to #2637
