### ISSUE TITLE
etcdctl ignores given `--peers` command line param

### ISSUE THREAD

**Issue by vanthome** [coreos/etcd#2601]
I cannot use the etcdctl command as I haven't bound it to 127.0.0.1. It tires to use `localhost` instead of the given peer address:

````
./etcdctl --debug --peers 192.168.10.1:2379 ls
Cluster-Endpoints: http://localhost:2379, http://localhost:2379, http://localhost:4001, http://localhost:4001
Curl-Example: curl -X GET http://localhost:2379/v2/keys/?consistent=true&recursive=false&sorted=false
Curl-Example: curl -X GET http://localhost:2379/v2/keys/?consistent=true&recursive=false&sorted=false
Curl-Example: curl -X GET http://localhost:2379/v2/keys/?consistent=true&recursive=false&sorted=false
Curl-Example: curl -X GET http://localhost:4001/v2/keys/?consistent=true&recursive=false&sorted=false
Curl-Example: curl -X GET http://localhost:4001/v2/keys/?consistent=true&recursive=false&sorted=false
Curl-Example: curl -X GET http://localhost:2379/v2/keys/?consistent=true&recursive=false&sorted=false
Curl-Example: curl -X GET http://localhost:2379/v2/keys/?consistent=true&recursive=false&sorted=false
Error:  501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
````

**Comment by yichengq** [comment]
etcdctl does the following things:
1. sync the cluster, and get the client urls registered in the cluster
You can get them also through https://github.com/coreos/etcd/blob/master/Documentation/other_apis.md#list-members
2. do requests using the client urls

Because the registered client urls are at localhost, it failed to list.

You can either set the correct client urls, or let etcdctl skip the sync step by using --no-sync flag

**Comment by yichengq** [comment]
Close due to low activity.

**Comment by jfoy** [comment]
I'm pretty sure this is still a live problem: https://gist.github.com/jfoy/c96fd9e3dbd44ea5385e

**Comment by jfoy** [comment]
Further, this works as expected if `--no-sync` is specified.
```
jacfoym2:discovery jfoy$ etcdctl --peers 172.16.206.252:2379 --debug --no-sync ls /
Cluster-Endpoints: http://172.16.206.252:2379
Curl-Example: curl -X GET http://172.16.206.252:2379/v2/keys/?consistent=true&recursive=false&sorted=false
```

**Comment by lordelph** [comment]
I have this same problem, using etcd and etcdctl  2.1.0-alpha.0

I've setup up 3 nodes using peer and client security. They are all peering successfully, and I can talk securely to them with curl.

I have exported environment variables for `ETCDCTL_CERT_FILE`, `ETCDCTL_CA_FILE`, and `ETCDCTL_KEY_FILE`. The ETCDCTL_PEERS value looks like this:

    ETCDCTL_PEERS=https://1.2.3.4:2379,https://5.6.7.8:2379,https://9.10.11.12:2379

Here's what happens with a simple `ls /`
~~~~~~~
$ etcdctl -debug ls /
Cluster-Endpoints: http://localhost:2379, http://localhost:2379, http://localhost:2379, http://localhost:4001, http://localhost:4001, http://localhost:4001
Curl-Example: curl -X GET http://localhost:2379/v2/keys/?consistent=true&recursive=false&sorted=false
Curl-Example: curl -X GET http://localhost:2379/v2/keys/?consistent=true&recursive=false&sorted=false
Curl-Example: curl -X GET http://localhost:2379/v2/keys/?consistent=true&recursive=false&sorted=false
Curl-Example: curl -X GET http://localhost:2379/v2/keys/?consistent=true&recursive=false&sorted=false
Curl-Example: curl -X GET http://localhost:4001/v2/keys/?consistent=true&recursive=false&sorted=false
Curl-Example: curl -X GET http://localhost:4001/v2/keys/?consistent=true&recursive=false&sorted=false
Curl-Example: curl -X GET http://localhost:4001/v2/keys/?consistent=true&recursive=false&sorted=false
Curl-Example: curl -X GET http://localhost:2379/v2/keys/?consistent=true&recursive=false&sorted=false
Curl-Example: curl -X GET http://localhost:2379/v2/keys/?consistent=true&recursive=false&sorted=false
Curl-Example: curl -X GET http://localhost:2379/v2/keys/?consistent=true&recursive=false&sorted=false
Curl-Example: curl -X GET http://localhost:4001/v2/keys/?consistent=true&recursive=false&sorted=false
Error:  501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
~~~~~~~

But with `--no-sync` it works
~~~~~~~~
$ etcdctl -debug --no-sync ls /
Cluster-Endpoints: https://1.2.3.4:2379,https://5.6.7.8:2379,https://9.10.11.12:2379
/foo
~~~~~~~~

This issue was closed with the comment "You can either set the correct client urls, or let etcdctl skip the sync step by using --no-sync flag"

How are the correct client URLs set? The only available option appears to be `--peers`. What are the ramifications of using `--no-sync`?

**Comment by lordelph** [comment]
I resolved this by ensuring the etcd service was started with a [advertise-client-urls](https://github.com/coreos/etcd/blob/master/Documentation/configuration.md#-advertise-client-urls) option.
