### ISSUE TITLE
etcdserver.Cluster may have inconsistent view with store for newly joined member when catching up the progress

### ISSUE THREAD

**Issue by yichengq** [coreos/etcd#2689]
Restriction:
1. rafthttp doesn't support talking to unknown member

Current workflow for newly joined member:
1. add new member to the cluster
2. start the new member with name and initial cluster(which contains name and peerURLs of each member)
3. the new member grabs the latest cluster info and etcd index from remote members
4. it assigns member ID to local cluster info, and record etcd index. It is important to keep latest peer URLs in the cluster here because it guides rafthttp how to talk to working members when they haven't appeared in the store.
5. *its cluster has inconsistent view with store from now on*
6. its cluster rejects to be recovered from a snapshot whose index is smaller than recorded etcd index(#2348) It may miss the latest Client URLs here.
7. its cluster rejects to apply conf change whose index is smaller than recorded etcd index(#2556)
8. its cluster should omit invalid updateAttributes request whose index is smaller than recorded etcd index(#2683, #2690 )
9. *it catches up the progress and its cluster have consistent view with the store*

In the process for newly joined member to catch up the progress and have consistent view with the store, its cluster runs in this way:
1. its ID and peerURLs are as new as remote members
2. its ClientURLs of known IDs are consistent with the store, and it doesn't have client URLs of unknown IDs(the ID that has been removed in the cluster)
3. its Names start from what are given in initial-cluster, and apply name change on known IDs.

**Known problems for this approach**:
1. users may get inconsistent member view during the process to catch up
2. etcd may fail to restart if killed during the process

The probability to meet the problem is low because 1. people don't add/remove member a lot 2. the catch-up process is short
So the solution is ok today.

If we want to fully resolve the problem, we need to remove the restriction(make rafthttp talk to unknown member). It may need 1-2 week to fully support it. If we do this, cluster can always have consistent view with the store.

/cc @xiang90 @barakmich

**Comment by xiang90** [comment]
@yichengq I think this is growing out of control. I think we should explore the original approach more. 

Instead of building a future view of the cluster, we simply add id->addr map to rafthttp and just enough for sending a rpc message (no streaming or any sort of connection keep alive). 

When adding a member from raft wal/conf snap, we do what we are doing in today's rafthttp.
When removing a mbmer from raft wal/conf snap, we do what we are doing in today's rafthttp.

The only change we need to make is to maintain the id->addr map in rafthttp instead of cluster. So cluster always represents the current view of the cluster and always be consistent with wal/snap.
