### ISSUE TITLE
Streaming watch with waitIndex only receives new events

### ISSUE THREAD

**Issue by fasaxc** [coreos/etcd#2854]
Using etcd 2.0.11, if I start a streaming watch with a waitIndex that is in the past then I only get a single event, instead of the whole event stream:

Make one write and get the etcd_index so I can poll on it later:
```
$ ./etcdctl set test-key 1
1
$ curl -X GET -v 'http://localhost:2379/v2/keys/test-key'
<snip>
< X-Etcd-Index: 4
<snip>
{"action":"get","node":{"key":"/test-key","value":"1","modifiedIndex":4,"createdIndex":4}}
```
Make some more writes, which will have indexes 5, 6, 7...:
```
$ ./etcdctl set test-key 2
2
$ ./etcdctl set test-key 3
3
$ ./etcdctl set test-key 4
4
$ ./etcdctl set test-key 5
5
$ ./etcdctl set test-key 6
6
```
Then start a streaming watch:
```
$ curl -X GET -v 'http://localhost:2379/v2/keys/test-key?wait=true&stream=true&waitIndex=4'
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 2379 (#0)
> GET /v2/keys/test-key?wait=true&stream=true&waitIndex=4 HTTP/1.1
> User-Agent: curl/7.38.0
> Host: localhost:2379
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: application/json
< X-Etcd-Cluster-Id: 7e27652122e8b2ae
< X-Etcd-Index: 9
< X-Raft-Index: 367
< X-Raft-Term: 2
< Date: Thu, 21 May 2015 03:50:23 GMT
< Transfer-Encoding: chunked
< 
{"action":"set","node":{"key":"/test-key","value":"1","modifiedIndex":4,"createdIndex":4},"prevNode":{"key":"/test-key","value":"1","modifiedIndex":3,"createdIndex":3}}
```
curl hangs at this point and never returns the next event.

**Comment by fasaxc** [comment]
(It works as expected if the `etcdctl set` calls are made after the streaming watch is started.

**Comment by bprashanth** [comment]
> if I start a streaming watch with a waitIndex that is in the past then I only get a single event, instead of the whole event stream

You only get the very next event, i.e it behaves like a normal watch but doesn't close the connection, which is confusing. If I do waitIndex=7 and the currentIndex=10, i would expect 8, 9 and an open connection that streams events thereafter. 

Implementing this feels racy, because we could miss an event if it arrives between the scan and adding the watcher (https://github.com/coreos/etcd/blob/master/store/watcher_hub.go#L55).

Returning a list of 8,9 so I can restart a stream watch with waitIndex=10 is also feels acceptable. This sounds easier to implement, because all we need is for scan to return a list instead of a single event:
https://github.com/coreos/etcd/blob/master/store/event_history.go#L58 (the rest of watcherhub.Watch will stay the same). 

@xiang90  thoughts?

**Comment by xiang90** [comment]
> Implementing this feels racy

Yea... You have to add it to the watcherHub with Index N and scan from the given index to N -1. Then it would be reliable.

**Comment by xiang90** [comment]
> Returning a list of 8,9 

Well... This is actually a watch that returns all available events. Streaming would work like today, which does not support from a given index.

**Comment by bprashanth** [comment]
> Streaming would work like today, which does not support from a given index.

So streaming=true,waitIndex=(x>0) is unsupported? Out of curiosity, why? it seems halfway there. Watching at index=0 is never safe because something could always slip in between the list and watch and we would never get it right? 

> Yea... You have to add it to the watcherHub with Index N and scan from the given index to N -1. Then it would be reliable.

Hmmm, even that feels racy but I haven't looked too deep into it. The Nth event could arrive just before we add the watcher, and that watcher won't be notified about N till N+1. I suppose locking across the scan would work (https://github.com/coreos/etcd/blob/master/store/watcher_hub.go#L72).

**Comment by xiang90** [comment]
> Out of curiosity, why?

The streaming api was an experiment. It is never documented. And yes, it is half-way there. I was trying to solve it back to 1.5 years ago.

If you want to work on this, then go for it. Or I can look at it again if you really need/want that feature.

**Comment by bprashanth** [comment]
Alright, I'll give it some thought when i have time

**Comment by fasaxc** [comment]
The reason that I want a streaming watch with waitIndex is that, without the waitIndex, it's not possible to do a GET to get the current state and then do a streaming watch to follow the progress since the initial GET.  The problem is that there could be changes between my initial get and the start of the streaming GET.

That is particularly problematic for large start-of-day recursive GETs since it's likely that someone else makes a change while you're parsing the recursive GET.

**Comment by bprashanth** [comment]
@fasaxc see https://github.com/coreos/etcd/pull/2879

**Comment by fasaxc** [comment]
Thanks @bprashanth, I'll keep an eye out for your fix landing in an upcoming version, then I'll be able to finish the python-etcd streaming watch feature (https://github.com/jplana/python-etcd/issues/105).

**Comment by xiang90** [comment]
We are probably not going to fix this for v2. This works well in v3.
