### ISSUE TITLE
can not remove member :context deadline exceeded

### ISSUE THREAD

**Issue by CaesarC** [coreos/etcd#3000]
after i add a member.i found name was empty in member list.so i add another member with another Port.in the end.i can't delete both of the 'empty name member' >.<
```
etcdctl member add infra2 http://192.168.1.100:2380
etcdctl member add infra2 http://192.168.1.100:2381
```
```
[root@localhost ~]# etcdctl member list
845887864a948ab6: name=infra0 peerURLs=http://192.168.1.122:2380 clientURLs=http://192.168.1.122:4001
b1f20c7efdadb120: name=infra1 peerURLs=http://192.168.1.3:2380 clientURLs=http://192.168.1.3:4001
bfcc59564d80c14e: name= peerURLs=http://192.168.1.100:2380 clientURLs=
d2691e8d2f5d8fa3: name= peerURLs=http://192.168.1.100:2381 clientURLs=
[root@localhost ~]# etcdctl member remove bfcc59564d80c14e
Recieved an error trying to remove member bfcc59564d80c14e: context deadline exceeded[root@localhost ~]# 
[root@localhost ~]# etcdctl member remove d2691e8d2f5d8fa3
Recieved an error trying to remove member d2691e8d2f5d8fa3: context deadline exceeded[root@localhost ~]# 
```

**Comment by xiang90** [comment]
@CaesarC You need to start the just added member. Then it will publish name and url information automatically. What you have seen is normal. And we have changed the output of etcdctl in the last release, it should show unstarted instead of an empty name and url.

Or after you increase the number of member from 3 to 4, you will not be able to remove the 4nd one until the 3rd starts. The reason is that you increase the majority from 2 to 3.
