### ISSUE TITLE
etcd2 service does not start

### ISSUE THREAD

**Issue by mmrvelj** [coreos/etcd#3082]
Hi all

I am new to coreos/etcd and while I am trying to setup CoreOS (v 681.2.0) cluster I get stuck already on the first step - I cannot get etcd2 service to work.

I prepared CoreOS install (with following cloud-config)

<pre>
#cloud-config

coreos:
  etcd2:
    discovery: https://discovery.etcd.io/85b1009e02...........
    advertise-client-urls: http://10.28.10.45:2379,http://10.28.10.45:4001
    initial-advertise-peer-urls: http://10.28.10.45:2380
    listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
    listen-peer-urls: http://10.28.10.45:2380
  units:
    - name: etcd2.service
      command: start
    - name: fleet.service
      command: start
    - name: 00-eth0.network
      runtime: true
      content: |
        [Match]
        Name=enp0s25

        [Network]
        DNS=192.168.1.251
        Address=10.28.10.45/24
        Gateway=10.28.10.254   

ssh_authorized_keys:
  - ssh-rsa  XX......
</pre>

With this I get machine to install and boot but etcd2 does not start:

<pre>
localhost ~ # systemctl status etcd2
etcd2.service - etcd2
   Loaded: loaded (/usr/lib64/systemd/system/etcd2.service; static; vendor preset: disabled)
  Drop-In: /run/systemd/system/etcd2.service.d
           └─20-cloudinit.conf
   Active: active (running) since Tue 2015-06-30 11:32:12 ; 626ms ago
 Main PID: 931 (etcd2)
   Memory: 2.5M
   CGroup: /system.slice/etcd2.service
           └─931 /usr/bin/etcd2

Jun 30 11:32:12 localhost systemd[1]: Started etcd2.
Jun 30 11:32:12 localhost systemd[1]: Starting etcd2...
Jun 30 11:32:12 localhost etcd2[931]: 2015/06/30 11:32:12 etcd: listening for peers on http://10.28.10.45:2380
Jun 30 11:32:12 localhost etcd2[931]: 2015/06/30 11:32:12 etcd: listening for client requests on http://0.0.0.0:2379
Jun 30 11:32:12 localhost etcd2[931]: 2015/06/30 11:32:12 etcd: listening for client requests on http://0.0.0.0:4001
Jun 30 11:32:12 localhost etcd2[931]: 2015/06/30 11:32:12 etcdserver: datadir is valid for the 2.0.1 format
localhost ~ # etcd2 --version
etcd version 2.0.10
localhost ~ # cat /run/systemd/system/etcd2.service.d/20-cloudinit.conf
[Service]
Environment="ETCD_ADVERTISE_CLIENT_URLS=http://10.28.10.45:2379,http://10.28.10.45:4001"
Environment="ETCD_DISCOVERY=https://discovery.etcd.io/8............"
Environment="ETCD_INITIAL_ADVERTISE_PEER_URLS=http://10.28.10.45:2380"
Environment="ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379,http://0.0.0.0:4001"
Environment="ETCD_LISTEN_PEER_URLS=http://10.28.10.45:2380"
</pre>

The only symptom I see is this message about datadir valid for 2.0.1 format. I am using 2.0.10

Could you give me any tips where to look for solution?

**Comment by yichengq** [comment]
Try `sudo journalctl -f -t etcd2`, and it may have more info.

**Comment by mmrvelj** [comment]
Here is result, I am still confused
<pre>
-- Logs begin at Tue 2015-06-30 11:24:04 . --
Jun 30 18:41:22 localhost etcd2[18093]: 2015/06/30 18:41:22 etcd: stopping listening for peers on http://10.28.10.45:2380
Jun 30 18:41:22 localhost etcd2[18093]: 2015/06/30 18:41:22 etcd: member c954ebd................0b30af5b has previously registered with discovery service (https://discovery.etcd.io/8..................), but the data-dir (/var/lib/etcd2) on disk cannot be found.
Jun 30 18:41:33 localhost etcd2[18113]: 2015/06/30 18:41:33 etcd: listening for peers on http://10.28.10.45:2380
Jun 30 18:41:33 localhost etcd2[18113]: 2015/06/30 18:41:33 etcd: listening for client requests on http://0.0.0.0:2379
Jun 30 18:41:33 localhost etcd2[18113]: 2015/06/30 18:41:33 etcd: listening for client requests on http://0.0.0.0:4001
Jun 30 18:41:33 localhost etcd2[18113]: 2015/06/30 18:41:33 etcdserver: datadir is valid for the 2.0.1 format
Jun 30 18:41:34 localhost etcd2[18113]: 2015/06/30 18:41:34 etcd: stopping listening for client requests on http://0.0.0.0:4001
Jun 30 18:41:34 localhost etcd2[18113]: 2015/06/30 18:41:34 etcd: stopping listening for client requests on http://0.0.0.0:2379
Jun 30 18:41:34 localhost etcd2[18113]: 2015/06/30 18:41:34 etcd: stopping listening for peers on http://10.28.10.45:2380
Jun 30 18:41:34 localhost etcd2[18113]: 2015/06/30 18:41:34 etcd: member c954ebde6.....30b30af5b has previously registered with discovery service (https://discovery.etcd.io/8...........), but the data-dir (/var/lib/etcd2) on disk cannot be found.
</pre>

Would you suspect on something really being issue with data format, or something else. Btw /var/lib/etcd2 folder is completly empty
<pre>
core@localhost ~ $ ls -ald /var/lib/etcd2
drwxr-xr-x 2 etcd etcd 4096 Jun 30 11:24 /var/lib/etcd2
core@localhost ~ $ ls -al /var/lib/etcd2
total 8
drwxr-xr-x  2 etcd etcd 4096 Jun 30 11:24 .
drwxr-xr-x 20 root root 4096 Jun 30 11:32 ..
</pre>

**Comment by xiang90** [comment]
@mmrvelj 

It means:
1. you reused the discovery token or
2. you used the same configuration for different members within the same discovery cluster.

You have to generate a new discovery token per bootstrap.

**Comment by mmrvelj** [comment]
I have generated new discovery token (I tried setup at least 3 times today from scratch), and token is shared between all members of cluster (currently I only added second member, but cluster will have 3 machines). I changed only IP address in the cloud config file of the machines, but even when I tried to setup only single machine I get the same error. 

I understood from docs that every member of the cluster should use the same token, but token should be fresh generated for the cluster. Is this correct?

**Comment by mmrvelj** [comment]
I got progress. I regenerated new token with size=2 and now my two prepared machines are alive. So this means that cluster will not work until size is matched?

**Comment by xiang90** [comment]
@mmrvelj Yes. You are right.

**Comment by xiaoke94539** [comment]
@xiang90 I'm running into a similar issue.  The problem is that before the cluster is formed (other machines are not online yet) and the current machine is rebooted, the etcd2 service will not start.  
This is with CoreOS 1000.0.0.

Logs:

Apr 13 18:26:43 veenatest1 etcd2[1183]: recognized and used environment variable ETCD_ADVERTISE_CLIENT_URLS=http://10.4.251.163:2379
Apr 13 18:26:43 veenatest1 etcd2[1183]: recognized and used environment variable ETCD_DATA_DIR=/var/lib/etcd2
Apr 13 18:26:43 veenatest1 etcd2[1183]: recognized and used environment variable ETCD_DISCOVERY=http://10.4.251.158:80/9a4a252e7f77e1226
Apr 13 18:26:43 veenatest1 etcd2[1183]: recognized and used environment variable ETCD_INITIAL_ADVERTISE_PEER_URLS=http://10.4.251.163:23
Apr 13 18:26:43 veenatest1 etcd2[1183]: recognized and used environment variable ETCD_LISTEN_CLIENT_URLS=http://10.4.251.163:2379
Apr 13 18:26:43 veenatest1 etcd2[1183]: recognized and used environment variable ETCD_LISTEN_PEER_URLS=http://10.4.251.163:2380
Apr 13 18:26:43 veenatest1 etcd2[1183]: recognized and used environment variable ETCD_NAME=e82c63becfb44466bde729a2ee469756
Apr 13 18:26:43 veenatest1 etcd2[1183]: etcd Version: 2.2.5
Apr 13 18:26:43 veenatest1 etcd2[1183]: Git SHA: bc9ddf2
Apr 13 18:26:43 veenatest1 etcd2[1183]: Go Version: go1.5.3
Apr 13 18:26:43 veenatest1 etcd2[1183]: Go OS/Arch: linux/amd64
Apr 13 18:26:43 veenatest1 etcd2[1183]: setting maximum number of CPUs to 2, total number of available CPUs is 2
Apr 13 18:26:43 veenatest1 etcd2[1183]: listening for peers on http://10.4.251.163:2380
Apr 13 18:26:43 veenatest1 etcd2[1183]: listening for client requests on http://10.4.251.163:2379
Apr 13 18:26:43 veenatest1 etcd2[1183]: stopping listening for client requests on http://10.4.251.163:2379
Apr 13 18:26:43 veenatest1 etcd2[1183]: stopping listening for peers on http://10.4.251.163:2380
Apr 13 18:26:43 veenatest1 etcd2[1183]: member "e82c63becfb44466bde729a2ee469756" has previously registered with discovery service token
Apr 13 18:26:43 veenatest1 etcd2[1183]: But etcd could not find valid cluster configuration in the given data dir (/var/lib/etcd2).
Apr 13 18:26:43 veenatest1 etcd2[1183]: Please check the given data dir path if the previous bootstrap succeeded
Apr 13 18:26:43 veenatest1 etcd2[1183]: or use a new discovery token if the previous bootstrap failed.
Apr 13 18:26:43 veenatest1 systemd[1]: etcd2.service: Main process exited, code=exited, status=1/FAILURE
Apr 13 18:26:43 veenatest1 systemd[1]: Failed to start etcd2.

**Comment by Titerote** [comment]
Same thing happened to me on CoreOS beta (1010.3.0)

**Comment by pineking** [comment]
@xiaoke94539 How to slove the problem as you describe?

**Comment by xiaoke94539** [comment]
@pineking No solution at this time.

**Comment by xiang90** [comment]
@xiaoke94539 

> Apr 13 18:26:43 veenatest1 etcd2[1183]: But etcd could not find valid cluster configuration in the given data dir (/var/lib/etcd2).

The etcd data dir got lost after reboot. That is why your etcd server failed. You need to preserve data dir.
