### ISSUE TITLE
etcd proxy with SRV bootstrapping fails to reresolve after catastrophic failure

### ISSUE THREAD

**Issue by spacejam** [coreos/etcd#3177]
Situation:
1. cluster created
2. several proxies are created on high-read application servers
3. n/2+1 nodes die, rendering raft-based cluster reconfiguration impossible
4. admin initializes a new cluster using a backup from the previous server
5. SRV record now points to new cluster
6. all application servers are still unable to read from the proxies, as they are trying to reconnect to the previous ensemble

This is only recoverable without restarting the proxies if one of the previous nodes is used for the replacement cluster, and listens on the same ports as its predecessor.

What do you think about triggering a re-resolution of DNS when all known peers are unavailable, and the stale read threshold has been crossed?

**Comment by xiang90** [comment]
It seems like this is not what etcd itself should solve. 

Basically you create a new cluster with different clusterID and the previous proxies cannot automatically connect to it. 

Probably you can point the proxies to domain names instead of IP addresses from the very beginning or you have to reconfigure the proxies by restarting it.

We might make proxies support runtime reconfiguration, but it is not on our recent road map.

**Comment by xiang90** [comment]
@spacejam Do you have what you want to know? I am closing this due to low activity. Feel free to ask more or reopen the issue. Thanks!
