### ISSUE TITLE
proxy loop detection

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#3317]
If the etcd member advertise bad client urls (a proxy's address), the corresponding proxy might forward request to itself and form a loop.

A common mistake is to advertise the client url as localhost, then the proxy will forward the request to localhost (its own iface).

See https://github.com/coreos/etcd/issues/2772#issuecomment-131982508

**Comment by AdoHe** [comment]
I will try to do this.

**Comment by xiang90** [comment]
@AdoHe That would be awesome.

**Comment by gyuho** [comment]
We have a fix here https://github.com/coreos/etcd/pull/3645, but it adds unnecessary complexity.
Proxy loop happens from misconfiguration, and it is immediately noticeable in the beginning of cluster set-up. Since we would like to keep code base as simple as possible, it is not worth covering all the edge cases like this.

If this becomes a problem, we will revisit.
