### ISSUE TITLE
log unused or unrecongnized env vars

### ISSUE THREAD

**Issue by robszumski** [coreos/etcd#3319]
During the 2.0.x to 2.1.x releases, a few flags were renamed and it's not clear what happened since env vars that aren't recognized are just silently ignored. Several users have been tripped up by this.

Can we log unrecognized env vars that start with `ETCD_`? This would provide a hint as to what happened at lest.

**Comment by robszumski** [comment]
Maybe even log recognized _and_ unrecognized vars.

**Comment by ecnahc515** [comment]
I think in general we need to print all configured and unconfigured config options at startup of etcd. This would be anything you can use for an environmental variable, or flag.

It's very common to print what config options are used, I think thats normal. But it's difficult sometimes to determine what *isnt* set, and that would be super helpful. So printing all configuration values would be good, set, or unset.

It's probably a bit verbose, but I think this could solve a lot of problems, and ideally since startup should happen rarely, the verbosity isn't a big deal. If anything, it could go into the debug log level probably.

I'm also a fan of @robszumski's suggestion of printing unrecognized environmental variables that start with ETCD_ but aren't defined.

**Comment by xiang90** [comment]
@robszumski @ecnahc515 We have around 40 env_vars and the number is still increasing. How about providing an endpoint to check the passing in flags and env variables?

**Comment by carmstrong** [comment]
:+1: 

I support the proposal of logging unrecognized envvars as `WARN` and recognized ones as `INFO`. Even if it's verbose, seeing them all at startup would be helpful.

**Comment by xiang90** [comment]
@robszumski @carmstrong @ecnahc515 OK. We will support it soon.
