### ISSUE TITLE
proposal dropped easily when connection with leader lost

### ISSUE THREAD

**Issue by yichengq** [coreos/etcd#3380]
When redirecting proposal, if the connection with leader lost, rafthttp will clear all proposals in buffer, and thus proposal is dropped.

Ideally we can put these requests into a limited queue and wait for the next leader or the connection comes back.

from https://github.com/coreos/etcd/issues/3279#issuecomment-130487660

**Comment by xiang90** [comment]
After a second thought on this, I think we should only retry proposal if there was a temp connection issues and should not wait and retry if the leader is lost.

The reason is that temp connection issue can recover fast, within in second. So the client will not feel it usually if we retry correctly at server side.

On the other side, a leader issues will require at least several seconds to recover, the client will probably timeout waiting for the response anyway. It does not worth the effort to retry the proposal at sever side internally.

/cc @heyitsanthony opinions?

**Comment by heyitsanthony** [comment]
@xiang90 your argument seems reasonable; if the receiver will time out waiting for the response on retry, it's probably better not to bother with retry at all

**Comment by xiang90** [comment]
This is not something easy to achieve right now. Check https://github.com/coreos/etcd/pull/4691#issuecomment-192539030. 

We will revisit this when we redesign the transport layer or this causes significant issues for our users.
