### ISSUE TITLE
client retry during degraded cluster state

### ISSUE THREAD

**Issue by patrickbcullen** [coreos/etcd#3425]
I have a 5 node etcd cluster. If I shutdown 1 server, the cluster is degraded but still able to accept writes because a quorum of nodes is available. I have noticed that the etcd/client package does not behave as expected in this situation. If I supply a list of all 5 servers it fails on the server that is down and returns an error rather than retrying the request on another server.

The problem code is the check for context.DeadlineExceeded here https://github.com/coreos/etcd/blob/master/client/client.go#L279. This is the error returned by the HttpClient when a server is down. It return this error rather than trying the next server in the list.

Is this a bug or I am misconfiguring the client in some way? I first noticed this in fleet when I was unable to bring up a new machine when only one etcd server was down (it retries forever on this error).

**Comment by yichengq** [comment]
The error indicates that context exceeds its deadline, so client returns instead of trying other endpoints.

@mischief I guess fleet does set context timeout, and it uses all time on one request for one endpoint. Maybe you could set `HeaderTimeoutPerRequest` in config(http://godoc.org/github.com/coreos/etcd/client#Config) to limit the time on one request.

**Comment by yichengq** [comment]
@patrickbcullen Could you try to set longer context timeout for each call, and set `HeaderTimeoutPerRequest` as a reasonable value(1s) in config? This should solve this issue.

**Comment by yichengq** [comment]
Close this due to low activity. Feel free to open new issue if this is still a problem.
