### ISSUE TITLE
short local import paths in .proto files

### ISSUE THREAD

**Issue by onlyjob** [coreos/etcd#3484]
45390b9 introduced regression causing FTBFS on Debian hence downstream(s) now need to carry a new patch to compensate for breakage. I would understand if path were pre-pended with `github.com/coreos/etcd/Godeps/_workspace/src/` as it is done for other bundled packages but trimming from `github.com/gogo/protobuf/gogoproto/gogo.proto` to `gogoproto/gogo.proto` seems to be completely wrong. Please revert.

**Comment by bdarnell** [comment]
Can you show the failure and how you're running the build? The proto files should be irrelevant since a normal "build from source" should use the checked-in `.pb.go` files.

Proto import paths are not go import paths; using `import "github.com/..."` in a proto file makes those proto files difficult or impossible to use in other languages. Any build scripts need to be updated to set appropriate proto include paths instead of using $GOPATH/src as the sole proto root.

**Comment by onlyjob** [comment]
I believe the particular failure is irrelevant as quite obviously the namespace was broken. Also it is inconsistent from how other bundled packages handle private import paths.
FTBFS happens on command

    protoc -I/usr/share/gocode/src -I/usr/include -Ietcdserver/etcdserverpb/ --gogo_out=etcdserver/etcdserverpb/ etcdserver/etcdserverpb/etcdserver.proto

I strongly disagree with "should use the checked-in .pb.go files". Best practice is to rebuild everything from source, using properly compartmentalised reusable system-wide libraries. Please note that `protoc` compiler is not "checked-in"  hence using pre-built `.pb.go` files is almost the same as to use checked-in pre-compiled binaries...

Please handle private paths consistently with `github.com/coreos/etcd/Godeps/_workspace/src/` prefix -- that's all I'm asking for. :)

**Comment by xiang90** [comment]
>  Best practice is to rebuild everything from source

I think `*.pb.go` is part of our source actually. You do not need to rebuild that part.

**Comment by bdarnell** [comment]
If you want to regenerate protos before building, that's fine, but do so with `scripts/genproto.sh` (which was changed in 45390b9 to support the new import paths). If you have your own invocation of `protoc` it's your responsibility to keep it up to date when genproto.sh changes.

**Comment by onlyjob** [comment]
@xiang90, We do need to re-build pre-built files. It is our (Debian) policy and best practice.

@bdarnell, I'm sorry for attempting to do the right thing but with all due respect it is not possible to use `scripts/genproto.sh` with release tarball in clean build environment (on buildd servers) without internet access. Besides `genproto.sh` set `PREFIX` that we deliberately not using in favour of system libraries.

How do you justify inconsistent breakage of canonical import paths?

I have all reasons to believe that the problem is not in build script.
I can fix it by replacing paths in all 4 affected files like 

~~~~
-import "gogoproto/gogo.proto";
+import "github.com/gogo/protobuf/gogoproto/gogo.proto";
~~~~

but it should not be necessary.

**Comment by bdarnell** [comment]
It sounds like what we need is to split `genproto.sh` up so that you can use the part that runs `protoc` and `sed` without the part that runs `go get`. Also, the `$PREFIX` in that script has nothing to do with system libraries (it's not `./configure --prefix`); it's only used as input to the `sed` scripts that work around bugs in `protoc-gen-go`.

The canonical import path for a `.proto` file is its `package` directive plus its filename: `gogoproto/gogo.proto`. This is the only form that works consistently across all languages' protobuf implementations. Using other imports like go-style `github.com/...` or java-style `com.whatever` may work in some languages but not others. To build proto files that span multiple projects, you must do one of two things: A) copy/symlink the proto files into the appropriate directory structure, or B) simulate the directory structure by manipulating the protoc import path.

**Comment by onlyjob** [comment]
Fair enough, I fixed the problem by changing `protoc` argument from `-I/usr/share/gocode/src` to `-I/usr/share/gocode/src/github.com/gogo/protobuf` in build script. Thank you for your considerations. As far as I'm concerned this bug can be closed.

**Comment by yichengq** [comment]
@bdarnell @onlyjob Glad to see the problem is solved. :)
