### ISSUE TITLE
feature: support symlinks/aliases in etcd

### ISSUE THREAD

**Issue by kayrus** [coreos/etcd#3654]
For example: make `/dir/key1` key available at `/dir1/myapp/key2`

**Comment by philips** [comment]
What is the use case?

**Comment by kayrus** [comment]
set global keys and override them in some specific dir or use symlink.

**Comment by raoofm** [comment]
:+1:

**Comment by xiang90** [comment]
@kayrus You can build a smart client to achieve the same thing by adding hints in the dir. The goal of etcd is a simple kv. This feature complicates the kv also affect the auth system.

**Comment by raoofm** [comment]
@xiang90 Though a smart client can achieve this, but having this in etcd could efficiently do it with user permissions too.

I mean etcd auth feature can be used with this feature and user roles can be managed really well.

Right now without this feature, if I want to store secret keys for applications and create users and roles

application-1
    user: app_1
    role: /v2/keys/app_1/*
            /v2/keys/app_2/secret
            /v2/keys/app_3/secret

application-2
    user: app_2
    role: /v2/keys/app_2/*
            /v2/keys/app_1/secret
            /v2/keys/app_3/secret

With the feature requested, it would be like
application-1
    user: app_1
    role: /v2/keys/app_1/*

and secrets could be a sym link in its own directory.

I gave an example with 3 apps. In my case number of applications is in hundreds and giving permissions is a headache.
.................................................................
On a separate note, even if a smart client can do the same, in an organization, where operation teams use tools with shell script using etcdctl for monitoring etc and apps use the http api which can handle but etcdctl clients may be not.

**Comment by yichengq** [comment]
I don't see there are many use cases around this feature so far. So I don't prone to implement this.

**Comment by raoofm** [comment]
@yichengq how about the use case i have mentioned above. This is a common use case where anyone who tries to use etcd's auth feature needs to give permissions too. 
May be people are not realizing this as they are not managing roles or are not much concerned about it right now as it has a alternative tedious solution too, so it is not a blocker.

I think it really solves role management in microservices architecture, where thousands of services interact and role management comes into play

But if you guys still feel like not implementing it, that is fine too :)

**Comment by xiang90** [comment]
@raoofm We are not going to implement it at lease for v2 as long as there is a work around.

**Comment by pjz** [comment]
This would definitely be useful because it allows efficient many-many relationships to be described.

/relationship/alice/bob ->data_ab
/relationship/bob/alice ->data_ab
/relationship/bob/carol -> data_bc
/relationship/carol/bob  -> data_bc

So: to find all of a user's relationships you can do range('/relationship/<username>',prefix=True).... but all the data is duplicated.  It would be nicer if we could somehow make '/relationship/bob/alice' a symlink to '/relationship/alice/bob'.  It's fakable now by putting some special 'check the other order' value into the duplicate key, but that ends up requiring more queries to get actual results.  

Proposed solutions: 
  1) symlink - in the returned kv's, `key` should be the pointed-to key, and there should be an additional `via` list that's the list of symlink-keys traversed to get to the primary key.  In the case of a 'dangling' symlink, the kv would be the same a the return of a deleted key: version 0, without a value.
  2) hardlink - in the returned kv `key` should be a list of keys that access this value.  Everything else is the same. No 'dangling links' are possible.   Making sure the data is deleted requires deleting all the keys (singly or in a txn).

**Comment by pjz** [comment]
@xiang90 maybe this could be reconsidered as a future feature?

**Comment by rainingmaster** [comment]
@xiang90 Hi, could you share how about this feature going?  Thanks.
