### ISSUE TITLE
better description of -initial-cluster-token flag

### ISSUE THREAD

**Issue by robszumski** [coreos/etcd#3690]
> Initial cluster token for the etcd cluster during bootstrap.

This doesn't tell me what you use this for. It actually prevents you from joining a node to the wrong cluster when you're operating more than one cluster, correct?

**Comment by xiang90** [comment]
@robszumski We do not describe configuration extensively in configuration.md. We were trying to keep it short. The full description of `initial-cluster-token` is in https://github.com/coreos/etcd/blob/master/Documentation/clustering.md#static.

It says: If you are spinning up multiple clusters (or creating and destroying a single cluster) with same configuration for testing purpose, it is highly recommended that you specify a unique initial-cluster-token for the different clusters. By doing this, etcd can generate unique cluster IDs and member IDs for the clusters even if they otherwise have the exact same configuration. This can protect you from cross-cluster-interaction, which might corrupt your clusters.

Do you think we should modify it and add to configuration.md or we should link it there?

**Comment by robszumski** [comment]
Can we just add:

"Initial cluster token for the etcd cluster during bootstrap. **Specifying this can protect you from unintended cross-cluster interaction when running multiple clusters.**"

**Comment by xiang90** [comment]
@robszumski Great suggestion. I will do it. Thanks.

**Comment by xiang90** [comment]
Fixed via #3847
