### ISSUE TITLE
client.GetUser fails on unmarshal returned user with role

### ISSUE THREAD

**Issue by yichengq** [coreos/etcd#3702]
1. create a role
2. create a user and grants the role to the user
3. get the user

fail with error: `GetUser json: cannot unmarshal object into Go value of type string`.

found when exploring #3675

**Comment by ark76r** [comment]
@yichengq 
I have no idea how to fix in without big changes in server API.

This is my preset user_auth.go file: https://gist.github.com/ark76r/21d880eb86d27642ab73
And this is my test code: https://gist.github.com/ark76r/dfdf766b4425617ee2ba

In the modUser function I've added small code to dump actual answer from the server:

    var user User
        dumpBody(string(body)) // <- here 
        err = json.Unmarshal(body, &user)

This is the dumpBody:

    func dumpBody(body string) {
        pc, _, _, _ := runtime.Caller(2)
        fmt.Println(runtime.FuncForPC(pc).Name())
        fmt.Println(">>>", body)
    }

I've run my tests, and I've got among the other things such output:

    github.com/coreos/etcd/client.(*httpAuthUserAPI).GetUser
    >>> {"user":"userA"}

    github.com/coreos/etcd/client.(*httpAuthUserAPI).GrantUser
    >>> {"user":"userA","roles":["roleA","roleB"]}

    github.com/coreos/etcd/client.(*httpAuthUserAPI).GetUser
    >>> {"user":"userA","roles":[{"role":"roleA","permissions":{"kv":{"read":["/roleA/path1/*","/roleA/path2/*"],"write":[]}}},{"role":"roleB","permissions":{"kv":{"read":null,"write":null}}}]}

    github.com/coreos/etcd/client.(*httpAuthUserAPI).RevokeUser
    >>> {"user":"userA","roles":["roleA"]}


If I get it properly, server sometimes returns roles as a list of strings, and sometimes as a list of objects of type Role.

This is why we have to have two definitions of the user: 

    type User struct {
    User     string   `json:"user"`
    Password string   `json:"password,omitempty"`
    Roles    []Role   `json:"roles"`
    Grant    []string `json:"grant,omitempty"`
    Revoke   []string `json:"revoke,omitempty"`
    }

and

    type User struct {
    User     string   `json:"user"`
    Password string   `json:"password,omitempty"`
    Roles    []string   `json:"roles"`
    Grant    []string `json:"grant,omitempty"`
    Revoke   []string `json:"revoke,omitempty"`
    }

And use first or second depending of the use case.
It's even more difficult, because almost all metods of interface AuthUserAPI jus delegate request to the function modUser and in this place I don't know what should I expect from the server.

And this is why I belive server's API has design error.
(of course it's 03:27am here, and I may be just to sleepy to see other solution)

**Comment by ark76r** [comment]
@yichengq 
I've prepared version of the AuthUserAPI covering all (I hope) cases.
There are also appropriate changes in etcdctl.

Check PR #3675
