### ISSUE TITLE
Question about a case of permanent quorum loss + disk full

### ISSUE THREAD

**Issue by mitake** [coreos/etcd#3791]
Hi etcd developers,

I'm considering a case like this: an etcd cluster loses quorum permanently (1 survivor node and 2 dead nodes) and there's no space for `etcd backup` in the survived node.

Current standard methodology of handling a case of permanent quorum loss is `etcd backup`. Removing failed nodes forcibly isn't provided intentionally for safety reason (https://coreos.com/etcd/docs/latest/runtime-reconf-design.html).
However, `etcd backup` needs extra disk space for saving data and its size is proportional to the size of data dir. If the data dir is large (e.g. 80% of the drive), allocating the space for saving data will be impossible.

Therefore I think providing another way of recovery would be valuable for handling such a case. For example, an offline tool for removing failed nodes from the raft log of living node. How do you think about this idea?

**Comment by yichengq** [comment]
> For example, an offline tool for removing failed nodes from the raft log of living node. How do you think about this idea?

This idea is dangerous. If you append removeNode entry to the log without consensus, you must change the clusterID in the WAL because it is no longer the same cluster. `etcd backup` does the cluster ID change.

> If the data dir is large (e.g. 80% of the drive), allocating the space for saving data will be impossible.

I think the limit of data dir, considering v3 case, is smaller than 30GB. People could allocate 60GB space for etcd data dir. If the disk is really small, we could backup it in the remote machine. I don't see the use case that you mentioned.

/cc @xiang90

**Comment by mitake** [comment]
> I think the limit of data dir, considering v3 case, is smaller than 30GB. 

I didn't notice the limit. 60GB would be reasonable space for users. Thanks a lot for your comments!
