### ISSUE TITLE
Can not set some value to a key

### ISSUE THREAD

**Issue by HuKeping** [coreos/etcd#3845]
Hi there,

It seems `etcd` server will use space to replace the `+`? I get 
```
{"action":"set","node":{"key":"/mykey","value":"A   Bug","modifiedIndex":63,"createdIndex":63}
```

when doing
```
curl -v http:/127.0.0.7:2379/v2/keys/mykey -XPUT -d value="A+++Bug"
```

Is this intentional or a bug?

**Comment by gyuho** [comment]
Please try `curl -L -XPUT http://localhost:2379/v2/keys/test -d value="He%2b%2bllo";`.
Seems like we need to encode as in URL when we send request through `curl`.
`etcdctl` does not need this. `etcdctl` works well with `+` sign.

@xiang90 Do we need to document this?

**Comment by HuKeping** [comment]
Not only curl, also via the http requst from `Golang` this will happen.

**Comment by gyuho** [comment]
Then I think it's expected since it's sent in URL format right? Did you try etcd client? https://github.com/coreos/etcd/tree/master/client

**Comment by gyuho** [comment]
`+` in URLs or `curl` commands is an encoded space `%20` in most environments.
As I commented above, you need to encode plus sign. You might want to check out
this man page http://curl.haxx.se/docs/manpage.html#--data-urlencode.

Closing this because this is expected behavior, and not etcd issue.

@HuKeping, please let us know if you still believe this is an etcd issue.

Thanks!
