### ISSUE TITLE
RFE: Option for listing hidden keys

### ISSUE THREAD

**Issue by mickep76** [coreos/etcd#3854]
Hi

Would it be possible to add an option to show hidden fields for a Get until v3 removes the hidden feature using a underscore prefix.

**Example:**
```go
    resp, err := ki.Get(ctx, key, &client.GetOptions{ShowHidden: true, Sort: sort, Recursive: true})
```

**Comment by jonboulle** [comment]
@mickep76 This isn't something we're going to do, but we might accept it if someone proposes an implementation. One requirement would be that it has to be opt-in at both the API level and the etcd server level (i.e. it would need to be a flag to the etcd binary to enable this behaviour).

**Comment by xiang90** [comment]
@mickep76 The original design for hidden key is to provide the security through obscurity. So we cannot change this behavior in v2 unless set via a server-side parameter. We have decided to remove this feature in v3 and support native ACL instead. I am closing since we have got a solution and this thread is low activity.
