### ISSUE TITLE
Can etcd push KV changes to clients proactively? And how?

### ISSUE THREAD

**Issue by gzliudan** [coreos/etcd#3965]
Hi:
    All. If client watch a key or directory, can etcd server push KV changes to clients proactively? So the client needn't to long pull changes. And how to realize this function?

With regards
Daniel

**Comment by xiang90** [comment]
@gzliudan 

> All. If client watch a key or directory, can etcd server push KV changes to clients proactively?

Now etcd server is pushing updates to client. I am not sure what you mean exactly. Probably you do not want to keep the long polling connection between client and server? If so:

> And how to realize this function?

We do not have plan to support it. Probably you can build your own proxy to do long polling to etcd, and build your own client that can register endpoint to that proxy so that the proxy can push updates to the clients.

**Comment by gzliudan** [comment]
I mean if clientA is watching key /key1, when clientB update /key1, etcd will tell clientA that /key1's value has been changed, clientA no need to do long polling. And how to config etcd and client to support this function? It seems http protocol is long polling.

**Comment by xiang90** [comment]
@gzliudan 

>  clientA no need to do long polling

It only means client A needs to create the connection and the server keeps it to enable pushing.  

>  And how to config etcd and client to support this function?

Again etcd does not support it. You can write your own proxy/client to do it. I am not sure what you want to achieve, but in most cases you do not need this feature.
