### ISSUE TITLE
Need a ConfigFromFile helper

### ISSUE THREAD

**Issue by liggitt** [coreos/etcd#4008]
Migrating from the legacy go-etcd client to the official client would be eased with a `ConfigFromFile` helper function that took a legacy config file and constructed a corresponding client Config object.

see https://github.com/kubernetes/kubernetes/issues/18760

cc @xiang90 @timothysc

**Comment by heyitsanthony** [comment]
Seems reasonable to have support for ingesting config from a file (or wherever) instead of expecting people to roll their own to do the same thing (especially if there are a lot of options). At the very least, new tunables could be supported "out of the box" with a standard config. Are there any downsides here aside from it being a little more code?

**Comment by ecnahc515** [comment]
I think this would be really great to add, particularly for clients, but also possibly for the server component as well. 

First reason is it makes sharing configuration easier. If I have 2 apps both using the etcd client libraries I could potentially use the same configuration file for both rather than having to duplicate every config option in my own apps.

Separating them also makes configuration isolated for the most part from invocation, which makes it easier to version configuration options. So with flags, you have to keep them around because even if they don't mean anything anymore, removing them will cause anything invoking the application to fail, whereas with a config file those configuration values could be removed and the app would still run simply ignoring the values in your config (assuming removing them was made backwards compatible). 

Config files are generally easier to template from the orchestration and configuration management point of view point of view.

Finally, it makes it easier to support live config reloading. Configuration could be reloaded and the app could validate the config and gracefully restart on a signal. This can be done with environmental variables as well, but it isn't as simple usually. This cannot be accomplished with flags at all. This o e primarily applies to the server but not necessarily.

**Comment by timothysc** [comment]
This would need to target 2.2 series to meet k8s 1.2 release time-frame, given etcd3's time-frame won't meet it.

**Comment by jonboulle** [comment]
@ecnahc515 I don't want to conflate client configuration with server, can you split that discussion out into a separate issue?

**Comment by xiang90** [comment]
@jonboulle done at https://github.com/coreos/etcd/issues/4009

**Comment by ecnahc515** [comment]
@jonboulle @xiang90 my first and 2nd points apply to both client and server

**Comment by mitake** [comment]
@liggitt @heyitsanthony @ecnahc515 I'm working on the mechanism for unified configuration management of etcd client in https://github.com/coreos/etcd/pull/3944 . Currently it just uses env vars for limited parameters but I can add a support for file based mechanism.

**Comment by timothysc** [comment]
@xiang90 is there any status update on this one?

**Comment by mitake** [comment]
hi @timothysc 

I'm writing the file based configuration. It can be found here: https://github.com/mitake/etcd/tree/client-config
I'll create a PR soon.

**Comment by liggitt** [comment]
@mitake does that allow setting a client cert/key?

**Comment by mitake** [comment]
@liggitt currently, no. But I can add the support after we can have a consensus on the initial design.
