### ISSUE TITLE
Wrong error code when deleting a directory

### ISSUE THREAD

**Issue by smurfix** [coreos/etcd#4075]
Assume a directory /foo, last modified at change 12345, and a node /foo/bar.

DELETE /v2/keys/foo?dir=true fails (108, directory not empty). That's correct.
DELETE /v2/keys/foo?dir=true&prevIndex=12345 fails (102, not a file). That's broken.
DELETE /v2/keys/foo?dir=true&prevIndex=999 fails (102, not a file). That's broken too.

What I want, of course, is for the second command to also return 108, and for the third to return (101, Compare failed).

Version: current master.

**Comment by xiang90** [comment]
@smurfix 

For 1, you did a Delete operation, the operation is OK but the directory is not empty. Thus 108 is returned.

For 2, 3, you did a CAS operation. The check of the operation first failed since it only supports keys not directory. https://github.com/coreos/etcd/blob/master/Documentation/api.md#atomic-compare-and-swap.

**Comment by smurfix** [comment]
This is CAD, not CAS. The documentation you linked to does not say that CAD only works on non-directories. At the very least this is an omission in the documentation.

Also, silently ignoring a parameter only some of the time is not a good idea.

Also², to atomically delete and re-create a directory without prevIndex support by the server is an interesting exercise which many users of etcd will find somewhat challenging (read "unable to implement without a race condition").

Thus I'd liek to ask you to consider implementing this feature (or at least accept a patch which does) instead of closing this bug.

**Comment by jonboulle** [comment]
It's not exactly silently ignored. But I agree we definitely need to
tighten up the API documentation here. I'm not too keen on changing the
semantic at this stage in the lifetime of the V2 API. @xiang90 this is a
non-issue in V3 right?

Matthias Urlichs <notifications@github.com> schrieb am Sa., 26. Dez. 2015
22:10:

**Comment by smurfix** [comment]
OK, not exactly "silently", but "behaves as if it's not present, and returns an error which the presence of the keyword is supposed to fix" comes close. I was tracing through my code for more than an hour today, trying to figure out which part of my latest batch of changes managed to delete the "dir=true" part …

**Comment by xiang90** [comment]
> This is CAD, not CAS. The documentation you linked to does not say that CAD only works on non-directories. At the very least this is an omission in the documentation.

CAS and CAD are a pair of compare operations. If you read the API doc, it says explicitly both CAS and CAD only works for keys. 

```
This (CAS) command will set the value of a key only if the client-provided conditions are equal to the current conditions.
```

in CAS section.

And 

```
This command will delete a key only if the client-provided conditions are equal to the current conditions.
```

in CAD section. 

keys and directories are different in the API docs:

```
The primary API of etcd is a hierarchical key space. The key space consists of directories and keys which are generically referred to as "nodes".
```

>  Also², to atomically delete and re-create a directory without prevIndex support by the server is an interesting exercise which many users of etcd will find somewhat challenging (read "unable to implement without a race condition").

v2 API has been there for over 2 years. You are the 1st people want that to work. I would love to learn your use case. I think there should be a work around to achieve what you want without CAS/CAD on directory.

> Thus I'd like to ask you to consider implementing this feature (or at least accept a patch which does) instead of closing this bug.

I close this issue since it reports as `Wrong error code when deleting a directory`. In fact, it works as expected.  Also we are open to suggestions/feature requests with use cases. 

> OK, not exactly "silently", but "behaves as if it's not present, and returns an error which the presence of the keyword is supposed to fix" comes close.

They are different issues.  We probably should have separated the errors returns for "deleting a dir but dir option is not set " and for "CAS/CAD on directory is not supported".
