### ISSUE TITLE
ETCD2 doesnt restart automatically after reboot

### ISSUE THREAD

**Issue by lmcdasm** [coreos/etcd#4538]
hello.
On the 9th attempt of getting a simple 3 node CoreOS cluster up and running on the system.  After figuring out that you really need to get the first node up and running with discovery before letting the others come online, after sorting out NTP issues and such. I had the system up to where etcd2 was running on all nodes and no errors.
Then I added the fleet service to my cloud-config (output below).  Rebooted my nodes, and now ETCD2 must be restarted manually on each node (errors about Locksmith not being able "unlocking old locks failed" - the retry it now up in the 5 minute range.

My questions are really this:

- During a power out, abnormal crash - how come ETCD2 doesnt recover on its own (regardless of cloud-config changes - i rolled them back (placing in the old config-drive) and still on reboot etcd2 did come back.

- My real issue is trying to get fleet started, from the logs it "says" that things are ok - but i think since ETCD2 is busted, i cant get further.

If i start ETCD2 (sudo systemctl start etc2), then etcd comes back on all nodes, but i get the 503 GooggleAPI error when running "fleetctl list-machines".   However, the systemctl -l status fleet shows its running and the last line shows says "Connection Established to ETCD (although its not marked etcd2 - but i think its cosmetic and ETCD (1) is not running anyhow".

Here is my cloud-config:

#cloud-config

coreos:
  etcd2:
     discovery: https://discovery.etcd.io/3be984bb9e987274528baa9bf7545d93
     advertise-client-urls: http://$private_ipv4:2379,http://$private_ipv4:4001
     initial-advertise-peer-urls: http://$private_ipv4:2380
     listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
     listen-peer-urls: http://$private_ipv4:2380

  fleet:
     public-ip: $public_ipv4
  flannel:
     interface: $public_ipv4

  units:
    - name: vmtoolsd.service
      command: start
      content: |
        [Unit]
        Description=VMware Tools Agent
        Documentation=http://open-vm-tools.sourceforge.net/
        ConditionVirtualization=vmware

        [Service]
        ExecStartPre=/usr/bin/ln -sfT /usr/share/oem/vmware-tools /etc/vmware-tools
        ExecStart=/usr/share/oem/bin/vmtoolsd
        TimeoutStopSec=5

    - name: oem-cloudinit.service
      command: restart
      runtime: yes
      content: |
        [Unit]
        Description=Cloudinit from VMware Backdoor

        [Service]
        Type=oneshot
        ExecStart=/usr/bin/coreos-cloudinit --oem=vmware

    - name: etcd2.service
      command: start

    - name: fleet.service
      command: start
  oem:
    bug-report-url: "https://github.com/coreos/bugs/issues"
    id: vmware
    name: VMWare
    version-id: "9.10.0-r3"

SYSTEM INFORMATION:
VMware 6.0.1 
Using OVF files  - coreos_production_vmware_ova.ova
Network is all routable and working (Nslookup, ping router,gw, ntp server, etc).

**Comment by gyuho** [comment]
@lmcdasm 


Sorry to get back to you this late. There are a lot of problems, so let's take it one by one.

> you really need to get the first node up and running with discovery before letting the others come 

Can you clarify? As long as the nodes in the cluster share the same token, it shouldn't matter.
`https://discovery.etcd.io/new?size=3` to get 3-node token, and when one nodes starts up, it will
wait until the other nodes become online. And then they will be able to proceed with leader election.

> During a power out, abnormal crash - how come ETCD2 doesnt recover on its own

What do you mean by power out? Was it power-out to partial nodes? If all nodes are down out of power,
there's no way that etcd recovers that by themselves. If power comes back and if you have etcd run
at start up, as long as etcd still uses the same token, they should be able to talk to each other back
and recovers the cluster state. There's not enough information, so I am not sure how exactly it was like
in your situation.

> i rolled them back

What did you roll back?

> ETCD2 is busted, i cant get further.

Please provide etcd related error logs

> but i get the 503 GooggleAPI error when running "fleetctl list-machines"

Could you provide that exact error message? Or `fleetctl` message so that I can ask someone?
And could you also reformat your cloud-config? It's hard to see which and which is your config
because of the markdown formatting.

**Comment by gyuho** [comment]
@lmcdasm Any updates? Please let us know if you still have any questions.

Thanks!

**Comment by xiang90** [comment]
@lmcdasm @gyuho I am closing this due to low activity. Please reopen if @gyuho's answer does not resolve the issue. Thanks.
