### ISSUE TITLE
Log if permissions on data dir aren't correct/readable

### ISSUE THREAD

**Issue by robszumski** [coreos/etcd#4637]
From StackOverflow: https://serverfault.com/questions/759953/etcd2-will-not-start-via-systemctl-on-coreos

Solved his own problem, but we could make it easier:

> When I first ran the command manually, I did it as the root user. Therefore the data directory was owned by root, not the etcd user. Changing the permissions fixed the issue. Still pretty terrible that it doesn't log that, even in debug mode...

**Comment by xiang90** [comment]
@robszumski etcd does log it. However, due to the journald issue, it does not show. 

etcd 2.2.4 should solve this issue by updating the log pkg we are using (coreos.com/pkg/capnlog). At etcd side, we cannot really do anything to help besides doing this (https://github.com/coreos/etcd/blob/master/Documentation/reporting_bugs.md#how-to-get-etcd-configuration-and-log-when-it-runs-as-systemd-service-etcd2service).

**Comment by xiang90** [comment]
I am closing this. If people still have issues with journald + systemd + coreos, we will open an issue on coreos/pkg/capnlog.
