### ISSUE TITLE
constant 10737418240 overflows int

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd#4700]
I have a [PR](https://github.com/kubernetes/kubernetes/pull/22604) which failed with following message:
```
etcd/storage/backend/backend.go:41: constant 10737418240 overflows int
```

Full log is [here](http://pr-test.k8s.io/22604/kubernetes-pull-build-test-e2e-gce/31894/).

Note that I am perfectly fine while using Go 1.5

**Comment by heyitsanthony** [comment]
From the logs: `+++ [0305 17:42:51] linux/arm: go build started`

32-bit builds aren't supported

**Comment by gyuho** [comment]
Yeah we define https://github.com/coreos/etcd/blob/master/storage/backend/backend.go#L41 with over int32 max.

**Comment by gyuho** [comment]
Maybe we should document that in backend package?

**Comment by xiang90** [comment]
@gyuho We can fix the build. But there might be other issues for 32bit. Basically, go has some additional requirement for 32bit to work well (padding when you want to access data atomically). We have a lot of dependencies and we cannot make sure everyone takes care of this additional requirement. So we say we do not really support 32bit.

**Comment by heyitsanthony** [comment]
Probably should have a better 32-bit build failure indicator than `overflows int`, at least. It's certainly been a source of confusion.

**Comment by hongchaodeng** [comment]
@heyitsanthony 
Can we fix the failure?

**Comment by heyitsanthony** [comment]
@hongchaodeng the sort of fix I have in mind would still be a build failure, just a less confusing one

**Comment by luxas** [comment]
`etcd` godeps haven't been a problem with `arm`
On the other hand `arm64` had a `boltdb` issue as you know #3830

@xiang90 Is it possible to include `arm`, `arm64` and maybe `ppc64le` in Travis build CI? 
Just thinking out loud about possible solutions.

**Comment by luxas** [comment]
Got it compiled on both `arm` and `amd64` by just
```go
// backend.go
InitialMmapSize int64 = 10 * 1024 * 1024 * 1024

// boltoption_unix.go
InitialMmapSize: int(InitialMmapSize),
```
WDYT? I may send a PR if it fixes the problem.

**Comment by xiang90** [comment]
@luxas We can fix the build, that is simple. But the thing is that there might be data races in 32 bit even if it builds and we are not going to fix them.

**Comment by xiang90** [comment]
@luxas In another word, we do not officially support or extensively test etcd on 32 bit.

**Comment by luxas** [comment]
@xiang90 What about `arm64` then?
I know the fix is simple, but I'd like to get it building at least. 
You know, `arm` support isn't enterprise support, it's build-your-own-lab support. So I'm not super-worried about maybe-data races that could exist. You don't have to support arm for that reason.
`arm64` on the other hand, could have enterprise interest.

I really do understand you, but I would be glad if the community would be allowed to make `etcd` build on arm at least. And a cross-build CI that tries to compile etcd for all arches go provides or just some of them would be an extra (cool) feature.

**Comment by xiang90** [comment]
@luxas I think arm64 can build as it is today. No? If you want to make it "builds". That is fine. Send a PR to us?

**Comment by luxas** [comment]
Yeah, `arm64` do build since #3830, but I wondered if you are "supporting" it when you just said no support for 32-bit.

@xiang90 How about the cross-build CI just for automatically knowing on which platforms it compiles, so any `arm` (or any other arch) breakers may be spotted already at PR review. Of course, because you're not supporting it, you may merge anyway, but the thing is that you always know whether it's building. Would shippable be an alternative?

**Comment by xiang90** [comment]
Now 32bit builds and complaints when starts, closing this.
