### ISSUE TITLE
etcdctlv3: ping command

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#4786]
Add a ping command that can ping each of the member and know about its health.

A ping should issue a linearized read.

If etcdctlv3 cannot reach to the member (network errors), then the member is unhealthy from the client's perspective. There might be an issue at client side or the member might be dead.

If linearized read succeeds, then the member is healthy and the cluster is healthy.

If linearized read fails, then the member is healthy but the cluster is not healthy from this member's perspective. Might be the member is partitioned or the cluster is not working.

**Comment by mqliang** [comment]
I am a little confused about this feature. It seems that  `etcdctl cluster-health` could also know about the members' and cluster's health status. 

Even if the member is partitioned, raft index of this member will not make progress and `/helath` endpoint will return `{"health": "false"}`. Cluster is healthy if majority (quorum) of etcd members are healthy, otherwise cluster is unhealthy.

**Comment by xiang90** [comment]
@mqliang This is for v3. Cluster health is confusing actually: see https://github.com/coreos/etcd/issues/3852

**Comment by xiang90** [comment]
closed via #4812
