### ISSUE TITLE
clientv3: watch api leaks go routine when connection is switched

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#5178]
When switch a connection, the watch API might leak a routine.

**Comment by heyitsanthony** [comment]
@xiang90 is there a way to reproduce this? The integration tests already extensively stress the reconnection path. I changed the tests to use a watcher client with multiple endpoints as well as tried killing the server backing the watcher instead of closing the active connection. No goroutine leaks.

**Comment by xiang90** [comment]
I will try to get a reproduce. I was able to reproduce this by running the client against the fault injected cluster.

**Comment by xiang90** [comment]
fixed in grpc https://github.com/grpc/grpc-go/issues/659
