### ISSUE TITLE
Etcd is always failed but netstat showing that the port actually being used by etcd

### ISSUE THREAD

**Issue by rvu95** [coreos/etcd#5688]
```bash
$ lsb_release -a                                                                                                                                                                    ‹ruby-2.3.0›
LSB Version:	1.4
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a

$ uname -a                                                                                                                                                    
Linux stuffed-cat 4.6.2-1-ARCH #1 SMP PREEMPT Wed Jun 8 08:40:59 CEST 2016 x86_64 GNU/Linux
```

Here the output I got when I'm starting the `etcd`:

```bash
$ sudo systemctl start etcd 
Job for etcd.service failed because the control process exited with error code.
See "systemctl status etcd.service" and "journalctl -xe" for details.
```

The output of `journalctl -xe`

```bash
$ journalctl -xe                                                                                                                                                                    ‹ruby-2.3.0›
Jun 16 11:25:12 stuffed-cat etcd[6566]: listen tcp 127.0.0.1:2380: bind: address already in use
Jun 16 11:25:12 stuffed-cat systemd[1]: etcd.service: Main process exited, code=exited, status=1/FAILURE
Jun 16 11:25:12 stuffed-cat systemd[1]: Failed to start etcd key-value store.
-- Subject: Unit etcd.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit etcd.service has failed.
-- 
-- The result is failed.
Jun 16 11:25:12 stuffed-cat systemd[1]: etcd.service: Unit entered failed state.
Jun 16 11:25:12 stuffed-cat systemd[1]: etcd.service: Failed with result 'exit-code'.
Jun 16 11:25:13 stuffed-cat sudo[6574]:     irvi : TTY=pts/6 ; PWD=/var/lib/etcd ; USER=root ; COMMAND=/usr/bin/systemctl start etcd
Jun 16 11:25:13 stuffed-cat sudo[6574]: pam_unix(sudo:session): session opened for user root by (uid=0)
Jun 16 11:25:22 stuffed-cat systemd[1]: etcd.service: Service hold-off time over, scheduling restart.
Jun 16 11:25:22 stuffed-cat systemd[1]: Stopped etcd key-value store.
-- Subject: Unit etcd.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit etcd.service has finished shutting down.
Jun 16 11:25:22 stuffed-cat systemd[1]: Starting etcd key-value store...
-- Subject: Unit etcd.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit etcd.service has begun starting up.
Jun 16 11:25:22 stuffed-cat etcd[6580]: recognized and used environment variable ETCD_DATA_DIR=/var/lib/etcd
Jun 16 11:25:22 stuffed-cat etcd[6580]: recognized and used environment variable ETCD_NAME=8a8cffe8564840ba8c7190bc88548868
Jun 16 11:25:22 stuffed-cat etcd[6580]: etcd Version: 2.3.1
Jun 16 11:25:22 stuffed-cat etcd[6580]: Git SHA: GitNotFound
Jun 16 11:25:22 stuffed-cat etcd[6580]: Go Version: go1.6.2
Jun 16 11:25:22 stuffed-cat etcd[6580]: Go OS/Arch: linux/amd64
Jun 16 11:25:22 stuffed-cat etcd[6580]: setting maximum number of CPUs to 4, total number of available CPUs is 4
Jun 16 11:25:22 stuffed-cat etcd[6580]: listen tcp 127.0.0.1:2380: bind: address already in use
Jun 16 11:25:22 stuffed-cat systemd[1]: etcd.service: Main process exited, code=exited, status=1/FAILURE
Jun 16 11:25:22 stuffed-cat systemd[1]: Failed to start etcd key-value store.
-- Subject: Unit etcd.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit etcd.service has failed.
-- 
-- The result is failed.
Jun 16 11:25:22 stuffed-cat systemd[1]: etcd.service: Unit entered failed state.
Jun 16 11:25:22 stuffed-cat systemd[1]: etcd.service: Failed with result 'exit-code'.
Jun 16 11:25:22 stuffed-cat sudo[6574]: pam_unix(sudo:session): session closed for user root
```

The output of `netstat`:

```bash
$ sudo netstat -lpn | grep 2380                                                                                                                    
tcp        0      0 127.0.0.1:2380          0.0.0.0:*               LISTEN      6499/etcd   
```

Any ideas why?

**Comment by xiang90** [comment]
@rvu95 I believe you already have one etcd running as netstat shows. That is why etcd fails to start due to address conflict.

**Comment by rvu95** [comment]
@xiang90 when i look into the status:

```bash
$ sudo systemctl status etcd                                                      ‹ruby-2.3.0›
● etcd.service - etcd key-value store
   Loaded: loaded (/usr/lib/systemd/system/etcd.service; disabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Thu 2016-06-16 12:50:26 WIB; 8s 
     Docs: https://github.com/coreos/etcd
  Process: 18513 ExecStart=/usr/bin/etcd (code=exited, status=1/FAILURE)
 Main PID: 18513 (code=exited, status=1/FAILURE)

Jun 16 12:50:26 stuffed-cat systemd[1]: etcd.service: Main process exited, code=exited, status=
Jun 16 12:50:26 stuffed-cat systemd[1]: Failed to start etcd key-value store.
Jun 16 12:50:26 stuffed-cat systemd[1]: etcd.service: Unit entered failed state.
Jun 16 12:50:26 stuffed-cat systemd[1]: etcd.service: Failed with result 'exit-code'.
```

**Comment by JayBee6** [comment]
@rvu95 I am getting the same error, do you remember the fix?

**Comment by rvu95** [comment]
@JayBee6 have you tried `journalctl -b -u etcd` to see `etcd` log?

**Comment by tangjiecheng79** [comment]
i am getting the same error, do you remember the fix ?

**Comment by prakashmirji** [comment]
is there a fix for this? i am seeing same error. etcd is in activating state. I get below error when i start the service

Job for etcd.service failed because a timeout was exceeded. See "systemctl status etcd.service" and "journalctl -xe" for details.

the journalctl -b -u etcd show below message

Apr 28 21:56:46 mip-bd-vm658.mip.storage.hpecorp.net etcd[12587]: raft2021/04/28 21:56:46 INFO: 205c340a3ea10f34 is starting a new election at term 634
Apr 28 21:56:46 mip-bd-vm658.mip.storage.hpecorp.net etcd[12587]: raft2021/04/28 21:56:46 INFO: 205c340a3ea10f34 became candidate at term 635
Apr 28 21:56:46 mip-bd-vm658.mip.storage.hpecorp.net etcd[12587]: raft2021/04/28 21:56:46 INFO: 205c340a3ea10f34 received MsgVoteResp from 205c340a3ea10f34 at term 635
Apr 28 21:56:46 mip-bd-vm658.mip.storage.hpecorp.net etcd[12587]: raft2021/04/28 21:56:46 INFO: 205c340a3ea10f34 [logterm: 1, index: 3] sent MsgVote request to 52f219cfc02b867f at term 635
Apr 28 21:56:46 mip-bd-vm658.mip.storage.hpecorp.net etcd[12587]: raft2021/04/28 21:56:46 INFO: 205c340a3ea10f34 [logterm: 1, index: 3] sent MsgVote request to c5d9d556fb95c991 at term 635
Apr 28 21:56:48 mip-bd-vm658.mip.storage.hpecorp.net etcd[12587]: publish error: etcdserver: request timed out
Apr 28 21:56:48 mip-bd-vm658.mip.storage.hpecorp.net etcd[12587]: raft2021/04/28 21:56:48 INFO: 205c340a3ea10f34 is starting a new election at term 635
Apr 28 21:56:48 mip-bd-vm658.mip.storage.hpecorp.net etcd[12587]: raft2021/04/28 21:56:48 INFO: 205c340a3ea10f34 became candidate at term 636
Apr 28 21:56:48 mip-bd-vm658.mip.storage.hpecorp.net etcd[12587]: raft2021/04/28 21:56:48 INFO: 205c340a3ea10f34 received MsgVoteResp from 205c340a3ea10f34 at term 636
Apr 28 21:56:48 mip-bd-vm658.mip.storage.hpecorp.net etcd[12587]: raft2021/04/28 21:56:48 INFO: 205c340a3ea10f34 [logterm: 1, index: 3] sent MsgVote request to 52f219cfc02b867f at term 636
Apr 28 21:56:48 mip-bd-vm658.mip.storage.hpecorp.net etcd[12587]: raft2021/04/28 21:56:48 INFO: 205c340a3ea10f34 [logterm: 1, index: 3] sent MsgVote request to c5d9d556fb95c991 at term 636

Any pointers to troubleshoot?

**Comment by MingWangSong** [comment]
{"level":"fatal","ts":"2022-07-27T08:01:16.260Z","caller":"etcdmain/etcd.go:204","msg":"discovery failed","error":"listen tcp 127.0.0.1:2380: bind: address already in use","stacktrace":"go.etcd.io/etcd/server/v3/etcdmain.startEtcdOrProxyV2\n\t/go/src/go.etcd.io/etcd/release/etcd/server/etcdmain/etcd.go:204\ngo.etcd.io/etcd/server/v3/etcdmain.Main\n\t/go/src/go.etcd.io/etcd/release/etcd/server/etcdmain/main.go:40\nmain.main\n\t/go/src/go.etcd.io/etcd/release/etcd/server/main.go:32\nruntime.main\n\t/go/gos/go1.16.15/src/runtime/proc.go:225"}
Is it the same problem? How to deal with it
