### ISSUE TITLE
etcd with tls auto-healing workflow

### ISSUE THREAD

**Issue by krish7919** [coreos/etcd#5778]
Hi,
I am trying to design a self-healing etcd cluster in which in case monitoring finds that a node is dead or it is too over-loaded, or maintenance, or etc., a service kicks in which spawns new etcd member, adds it to the cluster and everything is normal again. This workflow seems to work fine so far.

Now, I want to take this to production & I am trying to use etcd with tls.
I am thinking of spinning up an instance with the certificates embedded in user-data file (for AWS EC2).
The major problem/confusion that I have is that for TLS to work, we need IP SANs, which is only available 'after' the instance spins up. I have no way of knowing this before-hand and I am stuck with this cyclic dependency of sorts.

Anyone has a hint about how to resolve this. Also, is there any way to work without IP SANs or with wildcards?
Thanks.

**Comment by xiang90** [comment]
Auto scaling is a bad idea. The more etcd members you have, the worse write and l-read throughput you would expect. Auto healing might make sense, you could use dns instead of ip address.

**Comment by krish7919** [comment]
@xiang90 alright, I can work with auto-healing! :)
Can you please elaborate on 'use of dns instead of IP address'?

**Comment by xiang90** [comment]
@krish7919 I think you can use domain name in alternative subject name. it is easy to know the domain name beforehand. i am not a security expert.

/cc @gtank might have better answer for you.

**Comment by gtank** [comment]
> The major problem/confusion that I have is that for TLS to work, we need IP SANs, which is only available 'after' the instance spins up.

Yes, this is the main problem we have with TLS support (it also affects Kubernetes). It can't be helped on cloud providers, but there are a couple of workarounds we've developed:

1. Use DNS SANs (instead of IP) that you can dynamically assign to particular hosts. This works, but means you'll pre-generate a bunch of key/cert pairs and store them around to distribute to new nodes. That's pretty common practice (though not great- you have to keep all those keys around on a single machine that could be compromised and mess with DNS).

2. Have the nodes check their own IP address on boot, generate a certificate signing request ("CSR") with the correct SANs, and submit it to a CA service. This ensures that the private keys are only ever on the host that will use them and scales better since it doesn't require pregeneration. The downside here is that you'll need an API-driven CA service - something like [Let's Encrypt](https://letsencrypt.org/), or [cfssl](https://github.com/cloudflare/cfssl) - to issue the certificates dynamically.

**Comment by xiang90** [comment]
@krish7919 I am closing this issue, since I think @gtank provides two approaches. The 1st one is what i suggested, but in more details.
