### ISSUE TITLE
cmux: needless use of fork?

### ISSUE THREAD

**Issue by onlyjob** [coreos/etcd#5860]
Etcd v3 gained dependency on [github.com/cockroachdb/cmux](https://github.com/cockroachdb/cmux) which is a fork of actively maintained [github.com/soheilhy/cmux](https://github.com/soheilhy/cmux). Any particular reason to use fork instead of original project?
Please consider using _soheilhy/cmux_ -- at least one can open a bug with the latter...

**Comment by xiang90** [comment]
This is not a unnecessary fork. We share part of the code logic with cockroachdb for handling connection multiplexing. They (cockroachdb) are maintaining the cmux lib actively. I would just use their fork for now unless there is an issue for us.

**Comment by onlyjob** [comment]
Needless forking is harmful. Both projects are active and the difference between them is not too great. They should probably work together in one repository...
Thank for your comment.

**Comment by xiang90** [comment]
@onlyjob Probably you should open an issue in cockroach/cmux. I would be happy to switch if they merge into one.

**Comment by onlyjob** [comment]
Thanks for suggestion. :) See https://github.com/soheilhy/cmux/issues/26

**Comment by shurcooL** [comment]
> Probably you should open an issue in cockroach/cmux.

https://github.com/cockroachdb/cmux does has its issue tracker disabled ([unlike](https://github.com/soheilhy/cmux/issues) the upstream repo).

**Comment by onlyjob** [comment]
Just as I suspected, `cockroachdb/cmux` is a "convenience fork": https://github.com/cockroachdb/cockroach/issues/7612#issuecomment-230348118
Whilst there _may be_ technical reasons to use _cmux_ from cockroachdb, I believe it is politically wrong because it encourages and reinforces fragmentation. Since upstream says that divergence between _cmux_ forks is minimal I suggest to consider switching to original _cmux_.

**Comment by xiang90** [comment]
@onlyjob I agree with you for most of the parts you mentioned. But as I mentioned, we share some of the code logic with cockroach. Right now, I would rather take a less risky approach by just using the fork. 
When I have time, I would love to check how much they diverged, and would love to make them converged by submitting prs and discussing the issues with the maintainers. However, I do not have enough time right now. 

If you really want to resolve the problem ("politically" and technically), I would suggest you to spend some time to fix the root cause. Thank you very much.

**Comment by onlyjob** [comment]
Fair enough, @xiang90. Thank you for your comments.
