### ISSUE TITLE
Cannot test errors from GetRole to differentiate role not existing from more general errors

### ISSUE THREAD

**Issue by bluepeppers** [coreos/etcd#5894]
After calling `AuthRoleAPI.GetRole`, and receiving a response where `err != nil`, I have no (sane) way of differentiating situations where `err != nil` due to the requested role not existing, and cases where `err != nil` due to a more generic error.

Below is an example of a function where I attempted to gain this functionality by repurposing `IsKeyNotFound` to test the error. Adding a `IsRoleNotFound` would solve this problem, though I don't know how scalable that is.

```
import (
	etcd "github.com/coreos/etcd/client"
)

//
// ...
//

func ensureDefaultUserRole() error {
	roleAPI := etcd.NewAuthRoleAPI(etcdClient)
	_, err := roleAPI.GetRole(context.TODO(), defaultUserRole)
	if err == nil {
		return nil

	} else if !etcd.IsKeyNotFound(err) {
		return errors.Wrap(err, "Failed to get default user role")
	}

	err = roleAPI.AddRole(context.TODO(), defaultUserRole)
	if err != nil {
		return errors.Wrap(err, "Failed to create default user role")
	}
	_, err = roleAPI.GrantRoleKV(context.TODO(), defaultUserRole, defaultUserRWPaths, etcd.ReadWritePermission)

	if err != nil {
		return errors.Wrap(err, "Failed to grant default user role")
	}
	return nil
}
```

**Comment by xiang90** [comment]
@mitake Can you please take a look?

**Comment by mitake** [comment]
@xiang90 @bluepeppers sure, I'm looking at the problem. I'll reply soon.

**Comment by mitake** [comment]
@bluepeppers 's idea of adding `IsRoleNotFound()` seems to be good to me. But currently it is hard because the error code isn't propagated well. It is because both of the server and the client library don't marshal and unmarshal error code:

- server side: https://github.com/coreos/etcd/blob/master/etcdserver/api/v2http/httptypes/errors.go#L31
- client side: https://github.com/coreos/etcd/blob/master/client/auth_user.go#L115

@xiang90 if the ignoring of the error code isn't intentional, marshaling/unmarshaling the code would be ok for the idea because it doesn't break compatibility of APIs. How do you think?
