### ISSUE TITLE
raft: discover and fix the clock drift of leader lease

### ISSUE THREAD

**Issue by swingbach** [coreos/etcd#6005]
I hope here is the right place to discuss about the issue

the current implementation of leader lease is based on the logical clock called tick, triggered by users in a certain interval outside the raft. but we may suffer from the problem of clock drift due to the delay of gc or scheduler, so the leader may hold its leader lease longer than it should.

since the interval of calling tick can be evaluated in the form of monotonic time, so how about recording monotonic time for each calling of tick function. then we can calculate the exact value of clock drift by comparing with the certain interval. we can also add the drift value up to the electionElapsed, so it can be accurate.

my concern is we may change the implementation of raft from logical clock into physical clock, and also it seems time.Now is walltime in golang, we may introduce some other libraries like [this](https://github.com/davecheney/junk/tree/master/clock) to implement monotonic time

hope to hear your thoughts

Thanks

**Comment by xiang90** [comment]
@swingbach 

I think we should still keep logic clock inside raft to keep raft easy to test and reason about. However, before raft tries to make any time related decision, it has to call external func to get the current logic time to be certain.

We do not have to trust go runtime timer. We can get the actual elapsed time from the hardware. So that the drift is bounded by the hardware, not NTP or other software.

**Comment by xiang90** [comment]
I am closing this out. We now support safe l-read which will not be affected by clock drift.
