### ISSUE TITLE
raft: some test fail if randomizedElectionTimeout equals electionTimeout

### ISSUE THREAD

**Issue by siddontang** [coreos/etcd#6068]
@xiang90 @swingbach 

For 
```
func (r *raft) resetRandomizedElectionTimeout() {
	r.randomizedElectionTimeout = r.electionTimeout + r.rand.Intn(r.electionTimeout)
}
```

Sometimes randomizedElectionTimeout equals electionTimeout, but some raft tests may fail, like:

```
--- FAIL: TestFreeStuckCandidateWithCheckQuorum (0.00s)
	raft_test.go:1336: state = StateCandidate, want StateFollower
	raft_test.go:1344: term = 1, want 2
	raft_test.go:1355: state = StateLeader, want StateCandidate
	raft_test.go:1359: term = 2, want 4
```

Reproduce when set`r.randomizedElectionTimeout = r.electionTimeout` directly in `resetRandomizedElectionTimeout`.

**Comment by swingbach** [comment]
@siddontang @xiang90 

I guess it's only a issue of test code and has nothing to do with the code of raft

the scenario we are trying to set up is letting the node's(say b) electionElapsed > electionTimeout so that it can vote for others when quorum checking is on,
but we also need to ensure its electionElapsed < randomizedElectionTimeout so it will not start to campaign for itself

one correction for this is simply set randomizedElection at least larger than electionTimeout

will fix it soon

**Comment by siddontang** [comment]
Hi @swingbach 
Where is the PR? I can't find it.

**Comment by xiang90** [comment]
@siddontang https://github.com/coreos/etcd/pull/6070
