### ISSUE TITLE
Need a way to know when `concurrency.Mutex` is no longer held

### ISSUE THREAD

**Issue by nekto0n** [coreos/etcd#6127]
Current implementation of `Mutex` provides no way for user to be notified when lock is no longer held, e.g. if lease expired due to connectivity problems, thus IMHO limiting it's use in real world environment.

**Comment by heyitsanthony** [comment]
@nekto0n I think right now `<-NewSession(client).Done()` will work? It's a little racey though since if the mutex session expires, calling NewSession() will allocate a new one; the `Done()` channel would need to be fetched before calling `Lock()`.

The concurrency constructors should probably just force everything to pass in a session instead of trying to fake a session per client like it does now. What do you think?

**Comment by nekto0n** [comment]
Or maybe `Lock()` itself could return `done` channel. Or, another approach - lock could accept a callable, which will be started/stopped upon lock/unlock events. Something like [that](http://pastebin.com/0j6d79aJ), but smarter.

**Comment by heyitsanthony** [comment]
@nekto0n `Lock()`/`Unlock()` probably should only have a synchronous interface in the client; better to keep the interfaces as simple as possible. That sort of callback interface can be layered on top of the base `Mutex` implementation if necessary.

It seems like all the concurrency primitives should be unified around `Session` since internally that's the liveness primitive and lock expiry is a subject of liveness. It also buys the option of resuming sessions if a client process is killed and then immediately restarted. Any objection to `NewMutex(s *Session, pfx string)`?

**Comment by nekto0n** [comment]
Maybe it will be useful to have an example in pseudo code, how typical use case could look like? Start from user story. Right now I think that user will have to manage two objects: `Session` (which can expire and needs to be recreated) and `Mutex.Lock` (which can fail because of session expiration or some other reason). Seems not very simple.

I've shown my use case. It boils down to some runnable entity, which should be run as cluster wide `singleton`, killed and restarted as needed. It would be nice if `runnable` itself would need to implement minimal contract, without knowing it is run under etcd lock. In Python and `gevent` we use `gevent.kill`, which raises special exception in greenlet, so only contract requirement to such `runnable` is "don't catch `GreenletExit` exception". In Golang I came up with a `CancellableFunc` which accepts `Context` and promises to finish as soon as context is cancelled.
I'm full open to new suggestions :)

>It also buys the option of resuming sessions if a client process is killed and then immediately restarted.

Sounds nice, but client would need to save `LeaseID` somewhere and then have a separate code path to check/ensure lease is still valid and start a new keepAlive loop explicitly.

**Comment by heyitsanthony** [comment]
@nekto0n You could have an abstraction that binds the session to the client instead of relying on `concurrency.Session` to do it. The client needs to be managed in some way regardless, so I don't think it's significantly more complicated than what's needed now for what you're suggesting:

Client with session attached:
```go
type sessionClient struct {
    *clientv3.Client
    s *concurrency.Session
    mu sync.Mutex
}

func (sc *sessionClient) Session() (s *concurrency.Session, err error) {
   sc.mu.Lock()
   defer sc.mu.Unlock()
   if s = sc.s; s != nil {
      select {
      case <-s.Done():
      default: return s, nil
      }
   }
   sc.s, err = concurrency.NewSession(sc, time.Second)
   return sc.s, err
}
```

Runnable with lock:
```go
func doRunnable(sc *sessionClient, runnable func(ctx context.Context) error) (err error) {
   s, serr := sc.Session()
   if serr != nil { return serr }
   m := concurrency.NewMutex(s, "lockpath")
   if err = m.Lock(context.TODO()); err != nil { return err }
   errc := make(chan error, 1)
   ctx, cancel := context.WithCancel(context.TODO())
   go func() { errc <- runnable(ctx) }()
   select {
   case err = <-errc:
       if uerr := m.Unlock(context.TODO()); err == nil {
           err = uerr
       }
   case <-s.Done():
       cancel()
       err = <-errc
   }
   return err
}

```

Does this seem like a reasonable model?

Mutexes should just lock/unlock and that's it; that interface is universal. The `Session` part is the distributed extension which is decoupled from the usual mutex interface. The `sessionClient` struct could possibly be made part of the concurrency package to emphasize the importance of a 1:1 relationship between clients and sessions, but I'm not sure whether it's worth the extra trouble.

Be careful about relying on the expiry path to enforce mutual exclusion. The session expiration could be delivered after a new client acquires the lock (e.g., the lease expires but `runnable` doesn't check `ctx.Done()` until some time after the fact). Access to etcd should be wrapped in a txn using `m.IsOwner()` to ensure exclusion. Access to resources outside etcd should account for possible overlap on expiry.

> Sounds nice, but client would need to save LeaseID somewhere and then have a separate code path to check/ensure lease is still valid and start a new keepAlive loop explicitly.

Well, yes. The lease id would need to be saved somewhere and the session resume path would need to call something like `SessionResume(clientv3.LeaseID) (*Session, error)` to check the lease and resume keepalives. It wouldn't be necessary, but a nice thing to have in some cases.

**Comment by nekto0n** [comment]
Looks really promising, except that `doRunnable` must be wrapped in a loop too in order to recreate `Session` and run again.

>Access to etcd should be wrapped in a txn using `m.IsOwner()` to ensure exclusion.
Oh, looked at this method and didn't understand it's purpose. Now I see that it is a fencing mechanism in case there is no other way in particular user model to perform CAS operation. Elegant thing.

**Comment by xiang90** [comment]
@heyitsanthony Shall we close this since https://github.com/coreos/etcd/pull/6172 is merged? Or we need to provide more utility functions?

**Comment by heyitsanthony** [comment]
@xiang90 I think this can be closed since, unlike before, it's possible to safely check the mutex's session liveness.

**Comment by xiang90** [comment]
OK. Closing.
