### ISSUE TITLE
Question about configuration file 

### ISSUE THREAD

**Issue by shuqilou** [coreos/etcd#6144]
we know that etcd can be started in three ways (in the old version): command line, environment variable, and configuration file. My question is why not started with the configuration file in the new version? As far as I know, the new etcd doesn't support the function of configuration file.

**Comment by heyitsanthony** [comment]
@shuqilou it's still supported. Use `etcd --config-file config.yml`. For an example configuration, see https://github.com/coreos/etcd/blob/master/etcd.conf.yml.sample

Loading from a config file isn't populating the configuration with the defaults in case the fields aren't set, so that's a bug. Will fix.

**Comment by xiang90** [comment]
@heyitsanthony is #6151 fixed this issue? shall we backport the fix?

**Comment by heyitsanthony** [comment]
@xiang90 only master is affected since `embed` is not in release-3.0. The example config works fine in 3.0.4.
