### ISSUE TITLE
Negative permissions for a role

### ISSUE THREAD

**Issue by johnbazan** [coreos/etcd#6293]
Hello guys, how are you?

I'm having a bad time while trying to revoke permissions from an specific folder for the guest role.

The scenario is the following:

 I want my guest role to be able to read and write to all the folders, with the exception of one.
The nodes that consume my etcd cluster should be able to write and read from anywhere (including the root path), but shouldn't be able to write at '/registry'.

I still need that more folders could be created at the root, so adding all the folders with -readwrite and just -read for '/registry' is not possible for me.

So, I wonder if there's some kind of negative permissions in etcd roles that allow me to do something like:

KV Read:
  /*
KV Write:
  /*
**KV Forbidden write:
  /registry**

Thank you very much.
Jonathan

**Comment by xiang90** [comment]
Sorry. No there is not. We do not have plan to support it either.

**Comment by johnbazan** [comment]
@xiang90 Thanks for the quick response!

Is there any workaround that you could recommend me?
I'm really struggling through this.

**Comment by xiang90** [comment]
@johnbazan Moving that "folder" out of registry would be the easier way. You can add a pointer to the original path to hint where the new folder is.

**Comment by johnbazan** [comment]
Sorry for the misunderstand, but moving it out to where?

(I still need my guest to be able to write to /* for backward compatibility reasons).

**Comment by jmdacruz** [comment]
@xiang90 I think what @johnbazan is trying to do is define an access control policy that has two rules: One that provides read/write access to "guest" for every folder in the root directory `/*`, and the other one that gives write permissions for `/special_folder` only to a particular user which has to be authenticated.

This situation happens when you have a deployment that is mostly open or "permissive", except for a few folders that need stringent access control. With the current implementation, it seems that @johnbazan would be forced to have to explicitly grant "guest" access to all the folders inside `/` (which can be hundreds), except for `/special_folder`. This means that he has to know in advance which folders will be created there. Creating a `/public` folder would solve the situation, but would create a (arguably small) backward compatibility problem (e.g., clients already writing into `/` would have to be reconfigured to use the `/public` prefix)

**Some random thoughts**: I'm guessing what you imply above is that etcd doesn't support policy/rule combining algorithms (a la XACML), hence this is not possible today. I agree this type of access control can be a bit more complex, but might be desirable in the future. And I don't mean implementing ABAC or XACML, but maybe just some simple policy combining rules. Moreover, have you consider completely externalizing access control as a separate module, providing a basic implementation and leaving more complex integrations to 3rd parties (think PEP/PDP model)?

**Comment by xiang90** [comment]
@johnbazan Sorry for the bad example. So what I suggested is to move the "folder" you want to have "deny" access out of the granted "folder". In your case, you already granted root to everyone so it is hard.

@jmdacruz The goal of the etcd auth model is to provide a way to isolate applications that uses etcd. It is not mean to be a full featured and complex auth system.

Basically you grant /application-A to role A, /application-B to role B. Root/admin users have the full access. Guest is just designed for transition purpose from non-auth to auth.

**Comment by jmdacruz** [comment]
Understood, @xiang90. Thanks for your feedback!

**Comment by johnbazan** [comment]
I will go ahead and close this issue, since it was a question.

Thanks for replying @xiang90.
