### ISSUE TITLE
etcd member unable to serve request on majority down in bootstrap

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd#6569]
Scenario:
I have 3 member cluster. When 2 goes down, I want to save a snapshot from the remaining one (called "A"). Unfortunately, A program exits with following error:
```
etcdserver: could not get cluster response from ...: i/o timeout
etcdmain: cannot fetch cluster info from peer urls: could not retrieve cluster information from the given urls
```

This happens during initialization stage during which the majority goes down too fast and the left couldn't even finish bootstrap.

Ideally, the minority could still retry connecting and serve client request, e.g. backup.

**Comment by xiang90** [comment]
Can you write a simple script to reproduce this?

**Comment by hongchaodeng** [comment]
@xiang90 
This only happen if no wal & snap exist.
I wonder if this is expected?

**Comment by xiang90** [comment]
It is not expected. No matter what, users should be able to get a snapshot from a running member.

**Comment by heyitsanthony** [comment]
@xiang90 the exit path is from https://github.com/coreos/etcd/blob/master/etcdserver/server.go#L294

I don't think it should return a snapshot in this case since it'll always return an empty snapshot; the member isn't really "running" yet. Suppose a new member tries to initialize but is partitioned from the rest of the client, if that returns a snapshot and it's treated as a backup then that's data loss.

Related: is it possible for a fresh member to initialize but not yet have the backend snapshot so it'll return an empty snapshot?

**Comment by xiang90** [comment]
@heyitsanthony 

Sorry. I did not really take a close look at the debugging line. Yea. The 3rd member is not really started, so not running yet. Then it is expected that it should not return any snapshot.

**Comment by hongchaodeng** [comment]
Sounds like this is expected and we should take that as all members lost.
Closing.
