### ISSUE TITLE
clientv3: add client side metrics

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#6711]
We do not have client side metrics reporting now. It is important for users that want to understand the load they sent to etcd. We use gRPC for the rpc layer and use Prom as the metrics reporting system. Fortunately, people already have gRPC + prmo integration: https://github.com/grpc-ecosystem/go-grpc-prometheus. We want to use it in our clientv3 lib.

/cc @sinsharat Can you work on this? Thanks!

**Comment by sinsharat** [comment]
Sure will start working on it.

**Comment by sinsharat** [comment]
@xiang90 From what i have understood, adding only the two lines just before grpc dial option in clientv3/client.go dial func will support the metrics:
```
// add metrics options
	opts = append(opts, grpc.WithUnaryInterceptor(prometheus.UnaryClientInterceptor))
	opts = append(opts, grpc.WithStreamInterceptor(prometheus.StreamClientInterceptor))

	conn, err := grpc.Dial(host, opts...)
	if err != nil {
		return nil, err
	}
```

Apart from this we will need to update the glide.yaml and lock.yaml file with github.com/grpc-ecosystem/go-grpc-prometheus entries,
Also will need to add the package github.com/grpc-ecosystem/go-grpc-prometheus under cmd/vendor folder.

Was able to build it with these steps.
Will test it by writing some code and update you on this.
Thanks!

**Comment by xiang90** [comment]
Right.

**Comment by xiang90** [comment]
@sinsharat We also need to write docs for it and probably manually test it to ensure it works.

**Comment by sinsharat** [comment]
@xiang90 sure will write docs for it once i am done testing on it.
I have one doubt, how to test it manually, since via code for testing it like a person writing clientv3 will need to call the api grpc_prometheus.EnableClientHandlingTimeHistogram() in order to enable metrics.

**Comment by xiang90** [comment]
@sinsharat Probably you need to write a small driver code for it. Using the client to issue some rpc calls, see the metrics actually changed.

**Comment by sinsharat** [comment]
@xiang90 can you elaborate more on the driver part, i didn't quite understand what exactly you meant.
Also i was thinking of writing a test case for it since the clientv3 supports creating a cluster so while testing we could have called the grpc_prometheus.EnableClientHandlingTimeHistogram(), checked the old metrics value, do a certain set of operation on the client and checked the new value on that to ensure the metrics functionality works.

**Comment by gyuho** [comment]
How about something like https://github.com/coreos/etcd/blob/master/integration/cluster.go#L755? And just do some basic parsing?

**Comment by sinsharat** [comment]
@gyuho thanks for the reference. Sure will look into it and check how can i do something similar for this.

**Comment by sinsharat** [comment]
@xiang90 I was able to test and verify whatever changes i have done is working fine. For this i started etcd manually and using the main code i had written was able to verify the metrics. Also for this i have written an example_metrics_test.go on the same basis under clientv3 package. The issue i am facing now is i am not able to test the clientv3 package since the test case TestDialTimeout is failing :-(. Giving the error as :
```--- FAIL: TestDialTimeout (2.38s)
	leak.go:96: Test appears to have leaked a Transport:
```
@gyuho : Need you help in making it run successfully.
Thank you!

**Comment by sinsharat** [comment]
@xiang90 What all things do you expect in documentation? Will document it accordingly.
Thank you!

**Comment by sinsharat** [comment]
@xiang90 Will start with document section now. Wanted to know what all things you expect in the documentation.
Thank you!

**Comment by xiang90** [comment]
@sinsharat Probably just add one sentence that we support client side metrics, link to https://github.com/grpc-ecosystem/go-grpc-prometheus for more details. Maybe also provide an example link to the example program you wrote. I would like to keep it as simple as possible for now.

**Comment by sinsharat** [comment]
@xiang90 I totally agree with you. I too was feeling there is not much to document. Will do the changes as per your suggestion.
Thank you!

**Comment by sinsharat** [comment]
@xiang90 i think this can be closed now. Let me know if there's anything which i can look into now.

**Comment by xiang90** [comment]
Closing. Thanks.
