### ISSUE TITLE
Configurable maxGapBetweenApplyAndCommitIndex

### ISSUE THREAD

**Issue by gyuho** [coreos/etcd#6824]
Can we make `maxGapBetweenApplyAndCommitIndex` configurable?

I ran benchmarks on current etcd, the first time since we introduced `maxGapBetweenApplyAndCommitIndex` https://github.com/coreos/etcd/blob/master/etcdserver/v3_server.go#L50

```go
# current
maxGapBetweenApplyAndCommitIndex = 1000
```

etcd returns tons of `error too many requests` errors for the `benchmark` command in our performance doc https://github.com/coreos/etcd/blob/master/Documentation/op-guide/performance.md.

```bash
benchmark --endpoints=10.240.0.38:2379,10.240.0.39:2379,10.240.0.40:2379 --conns=100 --clients=1000 \
    put --key-size=8 --sequential-keys --total=100000 --val-size=256
```

I manually hard-coded the limit to `10000` and did

```
benchmark --endpoints=10.240.0.38:2379,10.240.0.39:2379,10.240.0.40:2379 --conns=100 --clients=1000 \
    put --key-size=8 --sequential-keys --total=2000000 --val-size=256
```

And etcd processed them all with no errors.

Test was done with the same machine spec in the performance doc.

I also checked the database and all 3 nodes `db` status look fine:

```
+----------+----------+------------+------------+
|   HASH   | REVISION | TOTAL KEYS | TOTAL SIZE |
+----------+----------+------------+------------+
| c6344c31 |  2000001 |    2000006 | 752 MB     |
+----------+----------+------------+------------+
```

/cc @xiang90 @heyitsanthony

**Comment by xiang90** [comment]
I do not think we should make it configurable, at least for now. 

The main reason we have this mechanism to avoid raft from accepting proposals faster than the applier can apply. 1,000 might not be a good value due to batching.

 Raft can batch nearly 1000 for one commit, this increase the gap suddenly to 1,000 and cause following proposals to fail.

I am fine to increase this number to 5,000 or so to alleviate the batching effect. Also now the expensive operations like range are moved out of raft, so they are cancellable. It is less a problem.

/cc @heyitsanthony

**Comment by heyitsanthony** [comment]
Bumping the gap seems OK for now. This path could stand to be a bit smarter in general by throttling or having a better feedback mechanism to detect runaway commit/apply gap widening.

**Comment by gyuho** [comment]
Sounds good. I will run more tests on 5,000 to make sure.
