### ISSUE TITLE
grpc-proxy need to work with client AutoSync

### ISSUE THREAD

**Issue by WangFenjin** [coreos/etcd#6902]
Please refer to this thread: https://groups.google.com/forum/#!topic/etcd-dev/wMCuWvYcsWM

Create an issue to track it.

**Comment by gyuho** [comment]
Comments from original post

>  If I setup grpc-proxy or etcd gateway in front of etcd cluster, and set up client to connect the `proxy`, should I enable AutoSync when new Client?
> 
> I noticed that:
> * If AutoSync not enabled and I restart `proxy`, the get/watch request will fail and never back to normal again. (And I even don't know the watch is failed as it's blocked there)
> * If AutoSync enabled, (according to the code) seems the requests will go directly to the etcd cluster, and the feature (cache, or coalesce watch) in grpc-proxy will never be used.
> 
> Could you help me about this? Thanks very much!

> For my first question: If AutoSync not enabled and I restart `proxy`, the get/watch request will fail and never back to normal again.
>
> I think it's also abnormal as I had passed multiple ip:port in new Client. I think the client should detect the failure and try another host.

**Comment by gyuho** [comment]
@xiang90 @heyitsanthony 

> We need to make either client understand gRPC proxy or gRPC proxy understand how to return members sync call.


Can you be more specific?

I think we need to define a separate RPC to trigger `Sync` call on grpc-proxy client, because we only want to update endpoints in grpc-proxy server side, but keep grpc-proxy server listen address in user client.

I am thinking

1. define a separate RPC or service (e.g., ProxySync) between grpc-proxy server and client
2. add a flag to clientv3.Config to note if this client talks to grpc-proxy or bare etcd cluster
3. if clientv3.Client talks to grpc-proxy server, the client calls `Client.ProxySync` rpc instead of calling `Sync` method

**Comment by heyitsanthony** [comment]
It doesn't sound like faithful proxying if the client needs to know whether it's talking to a proxy to work as usual.

Sync only needs to know the cluster member list-- the proxy can use that. Some options:
a) proxy responds to list request with member list changed to list only proxies
b) proxy mostly preserves member list but rewrites advertised client addresses to proxy addresses
c) extend the member list response protobuf to have something like `repeated Member  proxies` so the proxy can attach a list of proxies

**Comment by gyuho** [comment]
> a) proxy responds to list request with member list changed to list only proxies

Wrap grpcproxy's MemberList call to return grpc-proxy server endpoints makes sense.


> b) proxy mostly preserves member list but rewrites advertised client addresses to proxy addresses

How do we rewrite the advertised client address for grpc-proxy? Think it's now bind to listener https://github.com/coreos/etcd/blob/master/etcdmain/grpc_proxy.go#L78?


And do we want to support call `Sync` directly to the client here https://github.com/coreos/etcd/blob/master/etcdmain/grpc_proxy.go#L100-L111, so that grpc-server itself keeps its latest endpoint. Otherwise, `option a` seems like the simplest solution.

Thanks.

**Comment by heyitsanthony** [comment]
1) The member list contains the list of the cluster members, the proxy can replace all the members with itself and advertising listener.Addr(). Ideally with this approach it'd be possible to add all the proxies on the system. This could be done by writing to some etcd prefix as proxies connect and watching on it to get the current list (can probably reuse the way it's done in clientv3/naming).

2) yes, the proxy should enable autosync for itself in some way and possibly be the default. No strong opinion on whether it needs an option.
