### ISSUE TITLE
use http.Request.WithContext instead of Cancel

### ISSUE THREAD

**Issue by heyitsanthony** [coreos/etcd#6953]
Available as of 1.7

**Comment by xiang90** [comment]
@sinsharat Can you help to fix this? We have a bunch of places using our own context to cancel http request. We can use https://golang.org/pkg/net/http/#Request.WithContext directly. This issue might take you some time to finish since we have http related code throughout the codebase. but you can start from rafthttp.

**Comment by sinsharat** [comment]
@xiang90 Sure will start looking into it.
Thanks!

**Comment by xiang90** [comment]
closed by #7269 + #7255

**Comment by xiang90** [comment]
@sinsharat Thanks a lot for taking care of this!

**Comment by sinsharat** [comment]
@xiang90 you are most welcome :)
