### ISSUE TITLE
Typo in docs on reading past keys

### ISSUE THREAD

**Issue by suranap** [coreos/etcd#6966]
The [docs here](https://github.com/coreos/etcd/blob/v3.0.13/Documentation/dev-guide/interacting_v3.md#read-past-version-of-keys) have a typo. It uses `foo9` but it should be `foo1`. 

Also, the issue template has a link on how to report a bug. But that link doesn't work. It should be this instead: https://github.com/coreos/etcd/blob/master/Documentation/reporting_bugs.md

**Comment by sinsharat** [comment]
@suranap its not a doc issue, its doing a get range request, which is correct. Since the keys present are only  foo and foo1 hence its displaying the same. If there were more keys like foo2 and foo3 with the current query it will display these keys as well.
Also as far as reporting bugs is concerned, the link given is a relative path to code and not a url. Hence the link clicking doesn't work which you are mentioning. At the end it's pointing to the same document.

**Comment by heyitsanthony** [comment]
@suranap `etcdctl get --rev=4 foo foo9` will fetch [foo, foo9). `etcdctl get --rev=4 foo foo1` will fetch [foo, foo1) so it won't pick up `foo1`. The example can probably be improved to better demonstrate how ranges work though...

**Comment by sinsharat** [comment]
@heyitsanthony shall i take this up since i only had mentioned this example in doc earlier i guess?

**Comment by heyitsanthony** [comment]
@sinsharat I already have the changes in mind, it'll be up in a few minutes

**Comment by sinsharat** [comment]
ok.
