### ISSUE TITLE
Correct way of checking for key existence during transaction?

### ISSUE THREAD

**Issue by dariopb** [coreos/etcd#7115]
Hi,

What is the right way to check for existence of a key during a transaction?

Checking for a version > 0 works as expected (evaluates to "false" if the key is not there and to "true" if it is present:

`
                var keyUtf8 = ByteString.CopyFromUtf8(key);
                TxnRequest txr = new TxnRequest();
                Compare c = new Compare();
                c.Key = keyUtf8;
                c.Target = Compare.Types.CompareTarget.Version;
                c.Result = Compare.Types.CompareResult.Greater;
                c.Version = 0;
                txr.Compare.Add(c);
`

But I can't not get the same result using the Create CompareTarget, always evaluates to "true":

`
                TxnRequest txr = new TxnRequest();
                Compare c = new Compare();
                c.Key = keyUtf8;
                c.Target = Compare.Types.CompareTarget.Create;
                txr.Compare.Add(c);
`

thanks!

**Comment by heyitsanthony** [comment]
Testing for CreateRevision > 0 should succeed iff the key exists.

What client library is this? I don't see a `CompareResult` in the second example, so maybe that's the problem?

**Comment by dariopb** [comment]
Yes, testing for CreateRevision > 0 with Create works as well. Maybe I'm misinterpreting the  meaning of CompareTarget.Create as "check if it exists" but it seems I need to provide the CreateRevision as well.
The code is c# calling the raw grpc wrappers.

**Comment by heyitsanthony** [comment]
@dariopb that's not what it means. The compare target is the field in the key-value metadata use for the comparison-- from the docs ` target is the key-value field to inspect for the comparison.` (https://github.com/coreos/etcd/blob/master/Documentation/dev-guide/api_reference_v3.md#message-compare-etcdserveretcdserverpbrpcproto).

There's no specialized key existence check in the grpc protocol since there's already several ways to do the check (version > 0, createrev >0 , modrev > 0).

**Comment by dariopb** [comment]
Thanks, it makes sense now. Closing.
