### ISSUE TITLE
etcd v3gateway vs v2proxy

### ISSUE THREAD

**Issue by raoofm** [coreos/etcd#7439]
Confused - sorry, this needs more clarity.

Currently upgrading v2 to v3.
Existing clients talking to v2 data store via locally running v2 proxy - we are leaving them as is and will slowly migrate in future.

My initial impression after reading v3 documents was v2 proxy and v3 gateway are exactly the same thing, just renamed so that a new v3 smart grpc proxy could be built. So is it right that gateway replaces v2 proxy.

Found no reference of configuring gateway in v3 configuration docs, instead found proxy configuration.

Found no reference of proxy in v3 op-guide, instead found gateway.

- Is it safe to assume v3 gateway replaces v2 proxy?

- Can the clients using v2 proxy still talk to etcd v3 and both v3/v2 data store? (Which was answered yes in #7344 for v2 store)

- Any difference between clients using v2 proxy and v3 gateway?

- Also the future clients should install gateway and not proxy?

- Is there a need to migrate existing clients using v2 proxy to start using v3 gateway?

**Comment by heyitsanthony** [comment]
> So is it right that gateway replaces v2 proxy.

Yes.

> Found no reference of configuring gateway in v3 configuration docs, instead found proxy configuration.

There's some documentation on the gateway in the op-guide: https://github.com/coreos/etcd/blob/master/Documentation/op-guide/gateway.md. A full list of command line options is available through `etcd gateway start --help`.  Is something missing?

> Is it safe to assume v3 gateway replaces v2 proxy?

It's similar but not exactly the same; it's only meant to forward tcp connections. The v2 proxy has metrics and more tunables since it exposes its own http handlers.

> Can the clients using v2 proxy still talk to etcd v3 and both v3/v2 data store?

No. The v2 proxy expects http. If you try to use a v3 client with the v2 proxy it will return `Error:  rpc error: code = 13 desc = transport is closing`.

> Any difference between clients using v2 proxy and v3 gateway?

I don't understand what this means. The v3 gateway should look like an ordinary etcd endpoint to the client and serve both v2 and v3 requests. The v2 gateway will not since it inspects the http connection so it will break v3 clients.

> Also the future clients should install gateway and not proxy?

Yes.

> Is there a need to migrate existing clients using v2 proxy to start using v3 gateway?

No, but the v2 proxy is not being developed beyond bug fixes.

**Comment by raoofm** [comment]
Thanks for your response.

Continuing the discussion at #7442 where v3 etcd upgrade fails v2 proxies without certs.

**Comment by raoofm** [comment]
last question.

can v3 gateway talk to both v2 and v3 data stores? My guess is no, only v3 store.
So unless data is migrated from v2 to v3, old clients should continue using v2proxy.

**Comment by heyitsanthony** [comment]
@raoofm clients accessing etcd through the etcd gateway can talk to both v2 and v3. All the gateway does is bridge raw tcp connections between the clients and the etcd servers. It knows nothing about any kind of specific protocol.

**Comment by raoofm** [comment]
So the v3 gateway can accept anything that an etcd member can accept. It is just kind of a simple load balancer.
Is it round robin or sticky to only 1 and changes only if the connection fails?

**Comment by heyitsanthony** [comment]
Round-robin.

**Comment by raoofm** [comment]
@heyitsanthony gr8 Thanks

**Comment by raoofm** [comment]
Is it a simple round-robin, weighted or dynamic?

**Comment by heyitsanthony** [comment]
Simple round-robin: https://github.com/coreos/etcd/blob/master/proxy/tcpproxy/userspace.go#L141

More policies can be added if it there's a need.

**Comment by aim4pole** [comment]
Is there a place where I can validate tcpproxy round robin is actually routing to the desired endpoints in order other than code.  Logs dont capture it.  I checked snap/wal. No mention
