### ISSUE TITLE
etcd.New dose not return error ASAP when using dial timeout

### ISSUE THREAD

**Issue by shafreeck** [coreos/etcd#7450]
When I use etcd clientv3. I noticed when I dialed to a stopped etcd server with a dial timeout, it does not return error (here is : `connection refused`) as soon as possible. It waits until timed out.

https://github.com/coreos/etcd/blob/master/clientv3/client.go#L353

```go
		select {
		case <-client.balancer.readyc:
			hasConn = true
		case <-ctx.Done():
		case <-waitc:
		}
```

Maybe we should check about client.dialerrc in this select to avoid waiting ?

**Comment by xiang90** [comment]
Seems ok with me. Can you submit a patch to improve this with a test? Thanks.

**Comment by xiang90** [comment]
@shafreeck 

@heyitsanthony is right. I was initially confused by line https://github.com/coreos/etcd/blob/master/clientv3/client.go#L222 when I saw the chan size is only 1.

It does seem that we will only return the first error encountered though.

How about exposing the error chan to users? So that user can see the errors and cancel the dialing as they want?

**Comment by xiang90** [comment]
@shafreeck kindly ping. do you think the suggested approach will solve your issue?

**Comment by shafreeck** [comment]
@xiang90 Maybe this is not friendly enough for a user. I am thinking about this. The actual requirement is this: return an error to user asap when no endpoint is available. 

It is better that the SDK detects the error and return as normal, so the user do not need to handle the error channel.

**Comment by xiang90** [comment]
> return an error to user asap when no endpoint is available.

what if some users do want the client library to retry until timeout?

**Comment by shafreeck** [comment]
@xiang90 I think it differs timed out error from other errors.  Timeout is only meaningful when something is blocked. Maybe we should let user retry when something error occurs before timed out?

**Comment by heyitsanthony** [comment]
@shafreeck It's still meaningful even if there's an immediate response. The server may be temporarily unavailable (e.g., some people launch their clients before the servers are guaranteed to be up). The etcd client can't interpret these errors since it's really up to the client about what to do in this situation. Why isn't an error channel appropriate here? It lets the user decide how to handle the error instead of forcing the etcd client to decide.

**Comment by shafreeck** [comment]
@heyitsanthony 
> Why isn't an error channel appropriate here? It lets the user decide how to handle the error instead of forcing the etcd client to decide.

I just want to keep the API clean and avoid exposing too many details which may be unnecessary.

GRPC has an option `WithBlock` that etcd does not use. Do you have considered it?

It looks OK to me to expose the error channel if there is no better solution.

**Comment by heyitsanthony** [comment]
> GRPC has an option WithBlock that etcd does not use. Do you have considered it?

Yes. It was in the client, but it did not interact well with having a grpc balancer so it was removed in 46765ad79c07d209796ae619a0dab30eb7249a21.

**Comment by gyuho** [comment]
Actually, in the process of rewriting client balancer, we are considering enabling `WithBlock` by default. /cc @jpbetz 

We will make sure to highlight this change in v3.4, if that happens.

**Comment by jpbetz** [comment]
`WithBlock` works fine with the new balancer. I'm in favoring of enabling it when `DialTimeout` is set on the v3 client, otherwise the timeout is not respected.
