### ISSUE TITLE
clientv3 better txn string compare functionality

### ISSUE THREAD

**Issue by msvechla** [coreos/etcd#7466]
Hello, 

Is there a way to do a more advanced string comparison in the transaction compare() block?
`resp, err := kvc.Txn(ctx).
		If(clientv3.Compare(clientv3.Value("testkey"), "=", "myhost")).
		Then(clientv3.OpDelete("testkey")).
		Else(clientv3.OpGet("testkey")).
		Commit()`

I put a json object as the value of a key in etcd. 
E.g.: 
- key `testkey`
- value `{"Hostname":"myhost","Creation_Date":"2017-03-09T16:20:14.907021+01:00"}`

In the transaction I now want to check if "Hostname" in my json is "myhost" and then delete the key. Unfortunately I can only check for "=" but not for a prefix for example.

Another possibility would be to do some string operations on `clientv3.Value("testkey")` inside the Compare() but that also doesn't work of course.

Do you have any idea on how to accomplish this?
Thank you!

**Comment by heyitsanthony** [comment]
etcd won't interpret the data in a value, but transaction can work if the data is in first normal form instead of a json blob.

Have separate keys for the hostname and the creation date:
```
testkey/host -> "myhost"
testkey/date -> "2017-03-09T16:20:14.907021+01:00"
```
(alternatively there could just be `testkey/host` and `testkey/json` if only the host matters for these queries)

The txn would be:
```
client.Txn(ctx).
    If(clientv3.Compare(clientv3.Value("testkey/host"), "=", "myhost")).
    Then(clientv3.OpDelete("testkey/", clientv3.WithPrefix())).
    Commit()
```

Another way to do it is store the host name directly in the key so that there's no need to inspect the value at all:
`mykeys/myhost -> {"Hostname":"myhost","Creation_Date":"2017-03-09T16:20:14.907021+01:00"}`

**Comment by msvechla** [comment]
Tank you! I completely forgot about the directories, I'm pretty new to etcd. That'll work. Thanks for the hint!
