### ISSUE TITLE
what will happen if someone change system time when etcd is running

### ISSUE THREAD

**Issue by YuleiXiao** [coreos/etcd#7565]
if etcd is running, someone change OS time. What will happen?

There are some strange problem on my program. No one write, but watcher receive the event.

From log, there is a time point that from 9 into 11, over one day. I am not sure if it is the problem.

**Comment by heyitsanthony** [comment]
It affects v2 TTLs since the system passes around timestamps; they may expire earlier or later than expected. For >=3.1, it shouldn't affect v3 leases since that uses a monotonic time; for 3.0 leases may expire earlier or later than expected. It's possible the watcher is seeing a key expire.

What's the watcher code look like?

**Comment by YuleiXiao** [comment]
sorry, maybe not this problem. Thanks very much.
