### ISSUE TITLE
In VM environment, disk sync latency make heartbeat timeout and cause leader eletction.

### ISSUE THREAD

**Issue by suteng** [coreos/etcd#7617]
In VM, disk sync latency some time will jump much longer than the heartbeat an will cause leader election.
Is raft support divide the heartbeat tick and persistent operation to tow different go chan or thread?

**Comment by heyitsanthony** [comment]
The disk latency is part of leader liveness. Suppose the leader takes a minute to fsync a log append to disk, but has a 1s election time out. Although the leader can possibly respond to network requests (e.g., heartbeats), it's effectively down because it can't commit any new proposals while waiting on the slow disk. Try increasing the cluster's `--election-timeout`?
