### ISSUE TITLE
Missing etcd-discovery in etcd3 grpc proxy / gateway

### ISSUE THREAD

**Issue by pizzarabe** [coreos/etcd#7690]
Maybe I miss something obvious but both etcd(2/3) and the etcdv2 proxy can use the -discovery flag to get information about the etcd member from another etcd (https://coreos.com/etcd/docs/latest/dev-internal/discovery_protocol.html, https://coreos.com/etcd/docs/latest/op-guide/clustering.html#discovery).

The new etcd3 proxy and gateway can use DNS SRV to get information about a cluster but not etcd discovery (https://github.com/coreos/etcd/blob/master/Documentation/op-guide/gateway.md, https://github.com/coreos/etcd/blob/master/Documentation/op-guide/grpc_proxy.md).

Removing that feature (without any reason?) might break functionalities for some users (e.g. I can not configure a etcdv3 proxy or gateway like I did with the etcdv2 proxy, So I can not use the v3 API at the moment).

Like I said, maybe there is a obvious reason to remove that feature but If not, I would like to get that :)

**Comment by fanminshi** [comment]
@pizzarabe the `-discovery` was not added to etcdv3 proxy and gateway.

@xiang90 @heyitsanthony any objections on not adding the --discovery flag? the logic is already in the v2proxy from https://github.com/coreos/etcd/blob/master/etcdmain/etcd.go#L263-L296.

**Comment by heyitsanthony** [comment]
Not really thrilled about having a dependency on the v2 API in v3 code since then there's no reasonable path to deprecate v2.

**Comment by xiang90** [comment]
>Not really thrilled about having a dependency on the v2 API in v3 code since then there's no reasonable path to deprecate v2.

agree

**Comment by pizzarabe** [comment]
So if I understand that correct, etcd discovery is v2 only (bc of the json?)?
If so, there should be a note or sth. 
The "Discovery Service protocol" is in the latest docs and the v3 clustering guide is referring to it too (and if there is no way to use it with the other "core" components(gateway, grpc proxy) of v3 you don't really want to use it)

**Comment by heyitsanthony** [comment]
@pizzarabe it was written against the v2 API; there's no v3 API equivalent. It's supported in the etcd server because the etcd server still supports both v2 and v3; the v2 discovery system was grandfathered just because it was never removed and it's still useful for bootstrapping. It's mentioned in the clustering guide because it's still supported for the etcd server.

The v3 gateway and v3 grpc proxy were written to be v3-only; adding v2 discovery to those components will make it more difficult to totally eliminate etcd's dependence on the v2 API in the future. Additionally, the gateway and grpcproxy are closer to client applications than a core etcd server. They don't participate in bootstrapping, which was original purpose of the discovery service, so it's probably not the best idea to support it for those bits anyway (i.e., it won't work if there's any membership reconfiguration).

**Comment by pizzarabe** [comment]
@heyitsanthony Okay, got it. 
Anyway, I still believe we should make a note in the design specs (https://coreos.com/etcd/docs/latest/dev-internal/discovery_protocol.html), that using etcd discovery is not supported by the etcd gateway/grpc proxy to prevent users depending on that discovery method (like I did (: )

**Comment by xiang90** [comment]
Closing this. We will not support this feature with the reasons given above.
