### ISSUE TITLE
put db file to memory

### ISSUE THREAD

**Issue by sandflee** [coreos/etcd#7698]
our team is using etcd and facing io problem, and @honkiko proposed a idea that "is it possible to put db file to a ramdisk?", we found it's possible because etcd could use wal and snapshot to do recover. this may improve performance significantly

**Comment by sandflee** [comment]
we planed to add a db subdir to data-dir, $ETCD_HOME/data/db, and mount this dir to memory, like 
 mount tmpfs  $ETCD_HOME/data/db -t tmpfs.  this change little to etcd and need some mannually op.
a another way may to using a memory-based db store.

**Comment by heyitsanthony** [comment]
> we found it's possible because etcd could use wal and snapshot to do recover. this may improve performance significantly

This won't recover correctly-- the db file is the v3 snapshot. The snapshot files are for v2 data.

Related: #7445

**Comment by xiang90** [comment]
> our team is using etcd and facing io problem,

What problem are you facing?

**Comment by sandflee** [comment]
we have a small k8s cluster , but etcd io util is very high about  80-90%. 
1,  about 50 kubelet nodes
2, 3 etcd nodes, version 3.0, not ssd, we did a benchmark with 1 client 1 connection,write QPS is about 50
3, we enabled quorum-read, I known 3.1 optimize this, but not using it yet
4, etcd applys about 500w logs one day,the pressure not just comes from k8s, but also our own module.

**Comment by sandflee** [comment]
I had done a test in a local cluster with one etcd .
1, put some etcd v3 data
2, stop etcd,  rm db file, touch a new db file
3, restart etcd, seems everything is fine, and could get the putted data
do I miss something?

**Comment by sandflee** [comment]
snapshot files are for v2 data, I wondered why not support v3 data? if we are using v3 data, it couldn't be snapshotted?  thanks @xiang90 @heyitsanthony

**Comment by heyitsanthony** [comment]
@sandflee the db file /is/ the v3 snapshot; v2 and v3 use different mechanisms to save snapshots. If the v3 data were stored in the v2 snapshot that would lead to poor v3 performance since etcd would have to track boltdb data in two places.

That test with removing the db file does not demonstrate it's safe. It's likely that etcd hasn't made any snapshots so all the data is still in the wal files, so etcd will replay the wal back into the db on reset. Try setting `--snapshot-count=10` and putting 100 keys. You'll see that etcd loses v3 data if `db` is removed.

**Comment by sandflee** [comment]
@heyitsanthony  thanks for classifying, setting --snapshot-count=10, I see the data lost.
But if we put db file to a tmpfs, store v3data in you called v2 snapshot, this could improve v3 performance especially for slow disks,  because snapshots are rare, and data are stored in memory. Thought?

**Comment by heyitsanthony** [comment]
I tested this with a disk. The performance improvement is not that great. I see about 1.3x speedup for `benchmark --clients=200 --conns=200 put --total=100000` when putting the `db` file on tmpfs. I then increased the db commit interval from 100ms to 1s and saw 1.37x improvement with the `db` file on disk (tmpfs with the ramdisk and 1s commit gives 1.44x). This is, of course, without changing the snapshot policy, so if this were made safe it'd be somewhat slower.

The downside to doing full snapshots like what you're proposing is it can lead to huge latency spikes during snapshots since it would need to copy the entire v3 database; this latency will interfere with the system's reliability and possibly induce leader elections. Additionally, it'll need some serious/risky modifications to the snapshot path that just doesn't seem worth it given that a similar performance boost can be obtained by increasing the commit interval.

**Comment by xiang90** [comment]
> 2, 3 etcd nodes, version 3.0, not ssd, we did a benchmark with 1 client 1 connection,write QPS is about 50
3, we enabled quorum-read, I known 3.1 optimize this, but not using it yet
4, etcd applys about 500w logs one day,the pressure not just comes from k8s, but also our own module.

use SSD; do not put applications and etcd on the same disk or even same machine. we are not going to optimize etcd for slow machine any time soon. 

the primary goal is to make sure etcd delivers stable and predictable performance.  doing a stw style full snapshot periodically is not an option for us.

**Comment by sandflee** [comment]
I did a benchmark  with 1 clients 1 conns, and got 10x speed up,  but as  @xiang90 said, slow disk optimize is not a option, close it ,  thanks your apply!

**Comment by xiang90** [comment]
@sandflee The fsync duration of you disk is around 20ms. it is slow for even HDD (~10ms should be normal). i guess there is some contention going on. normally speaking, HDD etcd cluster can support up to 50 nodes k8s cluster without a problem.

**Comment by sandflee** [comment]
yes, what we concern is if the num of k8s nodes increased to several hundreds，could etcd support it in our env. By the way, I understand slow disk is not a optimize option for etcd, but there seems many users not use ssd in real production.
