### ISSUE TITLE
Ruby: WatchCancelRequest Confusion 

### ISSUE THREAD

**Issue by davissp14** [coreos/etcd#7742]
I just had a quick question on the proper way to cancel watch requests.
https://github.com/davissp14/etcdv3-ruby/blob/master/lib/etcdv3/etcdrpc/rpc_pb.rb#L153-L155

Looking at the code, the input and output of the WatchCancelRequests just like WatchCreateRequests are handled in a bi-directional stream. 

So if we create an active watcher by doing the following:
```
# Stub out the create request
stub = Etcdserverpb::Watch::Stub.new('localhost:2379', :this_channel_is_insecure)
create_req = Etcdserverpb::WatchCreateRequest.new(key: 'hi')
watch_req = Etcdserverpb::WatchRequest.new(create_request: create_req)

# Start listening for key changes in a new thread.
th = Thread.new do
  stub.watch([watch_req]).each{|resp| puts resp }
end 
```

Then we go ahead and create the cancel enum.   
```
cancel_req =  Etcdserverpb::WatchCancelRequest.new(watch_id: 0)
watch_req = Etcdserverpb::WatchRequest.new(cancel_request: cancel_req)

# This returns a Enumerable that i'm not sure what to do with.
stub.watch([watch_req])  
```

1. Given that the cancel request simply returns an enumerable, what's the proper way to cancel an active watcher.  If I issue `.each` and wait it just blocks forever and new events keep coming in.
2. Is the cancel request any different than simply sending an interrupt to the Thread?  

If this question would be better suited in the Grpc project, let me know!

**Comment by heyitsanthony** [comment]
@davissp14 I'm not familiar with ruby so I can't really comment on the grpc bindings, but I can explain how etcd's RPC watch protocol works, if that helps.

The cancel request will stop etcd from issuing events for a given watch id on a grpc watch stream. For example, if you have four watches open on a single stream but only want to stop receiving events for a single watch, the way to do it is to issue a cancel request with the watch id X you want to stop. etcd will acknowledge the watch for X is canceled by sending a watch response with canceled = true and  watchid=X. After that, the etcd server should not deliver any new events on that watch id over that stream.

If your client only has one watch per stream, it suffices to tear down the stream entirely via grpc instead of issuing a cancel request.

**Comment by xiang90** [comment]
@davissp14 does @heyitsanthony's answer solve your problem? can we close this?

**Comment by davissp14** [comment]
Yes, thank you!
