### ISSUE TITLE
not enough arguments in call to runtime.AnnotateContext

### ISSUE THREAD

**Issue by juaby** [coreos/etcd#7772]
[juaby@juaby src]$ go get google.golang.org/grpc
[juaby@juaby src]$ go get github.com/coreos/etcd/clientv3
# github.com/coreos/etcd/etcdserver/etcdserverpb
github.com/coreos/etcd/etcdserver/etcdserverpb/rpc.pb.gw.go:614: not enough arguments in call to runtime.AnnotateContext
	have ("golang.org/x/net/context".Context, *http.Request)
	want ("golang.org/x/net/context".Context, *runtime.ServeMux, *http.Request)

**Comment by heyitsanthony** [comment]
Please use golang vendoring like I've suggested instead of relying on `go get`. Otherwise you're building code against  unstable dev branches instead of tagged releases.

This is in grpc-gateway 1.2.2 but that won't build against the latest go-grpc release, only go-grpc master. I can't revendor grpc-gateway until go-grpc does a release including the interface update.

**Comment by xiang90** [comment]
go get wont always work well due to deps management issues. you can find the deps of clientv3 at https://github.com/coreos/etcd/blob/master/glide.yaml (replace master with your git hash). 

this yaml is messy for client usage since it also contains the deps that etcd server/ctl have. we might generate a dedicated dep yaml for client library in the future. but it is not very high priority thing for us. if you have time, you can help. thanks.

**Comment by lostinblue** [comment]
Using glide, and after a glide install with no errors, I still get this error when compiling. Has anyone had this happen too?

**Comment by MelleKoning** [comment]
Yes. What stable version of grpc should we use

**Comment by heyitsanthony** [comment]
@MelleKoning use the grpc and grpc-gateway versions that etcd vendors-- see https://github.com/coreos/etcd/blob/master/glide.yaml
