### ISSUE TITLE
see "mvcc: required revision has been compacted" even if data with specify revision exsit

### ISSUE THREAD

**Issue by sandflee** [coreos/etcd#7794]
1. etcdctl put a b , get revision 1
2. etcdctl put  b c, to increase revision
3. etcdctl compaction 2
4. etcdctl get a --rev=1 will see the error. but etcd get a will see the value with rev 1
 is this expected?  seems we should get the data for the revision

**Comment by heyitsanthony** [comment]
@sandflee compact removes historical keys that are older than the compaction revision; the most recent revision will always remain available.

**Comment by heyitsanthony** [comment]
It's unreliable to try to return the view of the store for a compacted revision since the key may have been removed. For the case with a single key that exists, etcd can satisfy the request, but for range operations I don't think it's possible to give a reliable result. In general, etcd will simply fail a compacted access instead of having extra logic to reason about it for these edge cases.

**Comment by sandflee** [comment]
I see this error in k8s(version 1.4) #watcher.go, though this did't exist in latest version, but may exist in other code
```go
	getResp, err := wc.watcher.client.Get(wc.ctx, wc.key, opts...)
	if err != nil {
		return err
	}
	wc.initialRev = getResp.Header.Revision

	for _, kv := range getResp.Kvs {
		prevResp, err := wc.watcher.client.Get(wc.ctx, string(kv.Key), clientv3.WithRev(kv.ModRevision-1))
		if err != nil {
			return err
		}
      }
```

**Comment by heyitsanthony** [comment]
@sandflee If the version of the key with a mod rev <= `kv.ModRevision-1` is compacted away, it's not in the store any more since `kv.ModRevision` supersedes it. `Get` will return an error. There's no way to fake it like in your first example where the requested revision is also the most current revision. What's your point?

**Comment by xiang90** [comment]
You can think of etcd has a layered structure. Each new change adds a new layer, which only contains the key change. 

4 ------------foo1(bar1')
3 ---foo(bar)---
2 ------------foo1(bar1)--------
1 ------------------------foo11(bar11)

You can look the key space from a top to bottom over all the layers. Or you can choose a layer to look down from. 

When you compact the keys, it removes the layers below the compaction revision. It also creates another as the base layer. The base layer contains all the keys that are in the compacted layers but do not have any layers on top of it.

compact 2

4 ------------foo1(bar1')
3 ---foo(bar)---
base ------------------------foo11(bar11)

hope this can help you understand everything.

**Comment by sandflee** [comment]
@heyitsanthony my point is this behavior seems not user friend,  by using etcdctl get foo, I could get foo with  rev 1, but if I use etcdctl get foo --rev=1, I got the above error if compact version larger than 1

**Comment by heyitsanthony** [comment]
@sandflee  [WithMinModRev](https://godoc.org/github.com/coreos/etcd/clientv3#WithMinModRev) and [WithMaxModRev](https://godoc.org/github.com/coreos/etcd/clientv3#WithMaxModRev) might be useful in this case.
