### ISSUE TITLE
about clientv3 watch context

### ISSUE THREAD

**Issue by YuleiXiao** [coreos/etcd#7860]
I use etcd clientv3 watch function with timeout context. If client can not connect to etcd server, it will return error, that is OK. But if connection is OK, but there is no event from server in time, it also return error.

I need the scene is that if the connection is not good, return timeout. If the connection is successful, there is no need to focus on the events returned time. Is there anyway to control it like this?

**Comment by heyitsanthony** [comment]
@YuleiXiao it would be something like:

```go
cctx, cancel := context.WithCancel(ctx)
wc := make(chan clientv3.WatchChan, 1)
go func() {
    wch := client.Watch(cctx, "abc", clientv3.WithCreatedNotify())
    wc <- wch
}()
select {
    case w := <- wch:
        return w
    case <-time.After(5 * time.Second):
        cancel()
        return nil
}
```

**Comment by YuleiXiao** [comment]
@heyitsanthony I do not want to cancle watch. The event is returning from time to time, I only watch watch a key and wait, maybe for a long time to return a event.

**Comment by YuleiXiao** [comment]
@heyitsanthony 
If etcd server not start, ```wch``` will return error. That is OK.
If etcd server is started, ```wch``` also return an error when timeout. That is my problem.

```
cctx, cancel := context.WithTimeout(ctx, time.Second)
wch := client.Watch(cctx, "abc")
```

**Comment by heyitsanthony** [comment]
@YuleiXiao that code will close the watch after one second because the context cancels after a second. It the context is canceled, the watcher will be canceled.

Under normal operation, if the connection cannot be established, the client won't return a watch channel. To be extra careful the `Watch` call can have a `WithCreatedNotify`, but the watch channel won't be returned until there a connection or the watcher interface is closed. For the code I gave, if the watch can't be established within the given time, it'll return `nil` to indicate the watch could not be established. What's it missing?

**Comment by YuleiXiao** [comment]
@heyitsanthony OK, I understand, thanks very much

**Comment by inksink** [comment]
I can not understand. @heyitsanthony @YuleiXiao 
If connection is failed when watching, watchChan will not stop waiting.
```
cli, err := clientv3.New(clientv3.Config{
    Endpoints:   endpoints,
    DialTimeout: dialTimeout,
})
if err != nil {
    log.Fatal(err)
}
defer cli.Close()

rch := cli.Watch(context.Background(), "foo")
for wresp := range rch {   
    for _, ev := range wresp.Events {
        fmt.Printf("%s %q : %q\n", ev.Type, ev.Kv.Key, ev.Kv.Value)
    }
}
```

Think about that connection is failed when `for wresp := range rch ` .

**Comment by gyuho** [comment]
@inksink It will block until a new connection comes back https://github.com/coreos/etcd/blob/master/clientv3/integration/watch_test.go#L178, afaik

**Comment by inksink** [comment]
@gyuho thanks. It's cool !
