### ISSUE TITLE
how to read values set by etcdctl with curl?

### ISSUE THREAD

**Issue by gunli** [coreos/etcd#8189]
Hi all,
I'm testing etcd 3.2.1.

1. I set a k/v by etcdctl with key=foo value=bar2
[user00@/data/home/user00/etcd-v3.2.1-linux-amd64]$./etcdctl get foo
bar2

2. I try to read the value by curl, but it gives me another value I set before
[user00@/data/home/user00/etcd-v3.2.1-linux-amd64]$curl -L http://localhost:2379/v3alpha/kv/range -X POST -d '{"key": "Zm9v"}'
{"header":{"cluster_id":"14841639068965178418","member_id":"10276657743932975437","revision":"6","raft_term":"3"},"kvs":[{"key":"Zm9v","create_revision":"2","mod_revision":"6",

my question is how to read this value by curl, what is the right URL?
Thanks.

**Comment by hexfusion** [comment]
> I set a k/v by etcdctl with key=foo value=bar2
[user00@/data/home/user00/etcd-v3.2.1-linux-amd64]$./etcdctl get foo
bar2

You mean `etcdctl put foo bar2` right?

> {"header":{"cluster_id":"14841639068965178418","member_id":"10276657743932975437","revision":"6","raft_term":"3"},"kvs":[{"key":"Zm9v","create_revision":"2","mod_revision":"6",

@gunli your response object appears to be truncated, but this otherwise this appears correct.  What you are possibly missing is the fact that key and value are base64 encoded.  So although you are passing a string 'foo' to etcdctl it is taking care of encoding it for you.  You are then using the base64 encoded value for the key foo 'Zm9v' when you call curl.  So the value would return 'YmFyMg==' for bar2, which is missing above because of truncation.  Does that make sense?

here is my reply from curl for the same call

{"header":{"cluster_id":"14841639068965178418","member_id":"10276657743932975437","revision":"3","raft_term":"2"},"kvs":[{"key":"Zm9v","create_revision":"2","mod_revision":"3","version":"2","value":"YmFyMg=="}],"count":"1"}

https://github.com/coreos/etcd/blob/master/Documentation/dev-guide/api_grpc_gateway.md

HTH

**Comment by gunli** [comment]
hi hexfusion,
 thank you for your replying.
 Yes, you are right, i etcdctl put foo bar2, and I try to read it with curl according to the methods in https://github.com/coreos/etcd/blob/master/Documentation/dev-guide/api_grpc_gateway.md, it gives me the wrong value, I don't know whether the URL<http://localhost:2379/v3alpha/kv/range> I passed to curl is right, should I pass it another URL? If yes, what is the right on?
Thank you.

[user00@/data/home/user00/etcd-v3.2.1-linux-amd64]$./etcdctl set foo bar3
bar3
[user00@/data/home/user00/etcd-v3.2.1-linux-amd64]$./etcdctl get foo 
bar3
[user00@/data/home/user00/etcd-v3.2.1-linux-amd64]$curl -L http://localhost:2379/v3alpha/kv/range -X POST -d '{"key": "Zm9v"}'
{"header":{"cluster_id":"14841639068965178418","member_id":"10276657743932975437","revision":"6","raft_term":"3"},"kvs":[{"key":"Zm9v","create_revision":"2","mod_revision":"6","version":"5","value":"YmFy"}],"count":"1"}

**Comment by raoofm** [comment]
@gunli It is because may be you are not setting ETCDCTL_API=3 environment property. You should do this before using etcdctl as a v3 client, else it will write into v2 data store. That is why you are able to retrieve the new value using curl with v2.

**Comment by xiang90** [comment]
@gunli As @raoofm mentioned, you need set env `ETCDCTL_API=3`.

**Comment by gunli** [comment]
@raoofm & @xiang90 Thank you, I got it. I get the right value after I set ETCDCTL_API=3.
