### ISSUE TITLE
etcd 2 to 3 upgrade docs need clarity around Ignition

### ISSUE THREAD

**Issue by pgburt** [coreos/etcd#8451]
A user [writes on twitter][tweet]:
> How to move from an cloud-init based etcd2.service to a ignition based etcd-member.service based server without downloading etcdv3 by hand?

I asked the user what docs they were referencing, and it seemed like they were looking at [this one][upgrade-doc]. It seems they decided to look at Ignition at the same time, and found themselves confused. We should clarify how to use Ignition + etcd together (and make it clear in docs like `etcd2 to 3`, where users are clearly lagging somewhat behind the latest and greatest trends).

[tweet]: https://twitter.com/arjanschaaf/status/901126184859312128
[upgrade-doc]: https://coreos.com/etcd/docs/latest/upgrades/upgrade_3_0.html

**Comment by xiang90** [comment]
@pgburt 

I am not sure this is something should be included in generic etcd doc. Container Linux is a special consumer of etcd, and has its own opinionated way to setup etcd. We'd either adding a special Container Linux focused doc in etcd repo, or explain this in Container Linux its own doc.

 Basically, we should not change the generic etcd upgrade doc to be container linux focused or make it appear so.

**Comment by heyitsanthony** [comment]
The cl doc at https://github.com/coreos/docs/blob/master/etcd/getting-started-with-etcd.md#setting-up-etcd  points to the generic upgrade advice, which is probably the source of confusion.

**Comment by arjanschaaf** [comment]
Sorry that was my rant on twitter 😁 
I've multiple 3 node etcd clusters running on CoreOS using etcd v2 for some time now using CloudInit configuration data. I've also created a new cluster using the Etcd v3 etcd-member.service examples in the CoreOS documentation. Both kind of setups work perfectly fine. So my next step would be to upgrade my existing v2 based clusters to v3 binaries. Not migrating v2 to v3 data, just replacing the binaries with the latest stable version and continuing to use the v2 API for now.

The only relevant documentation I could find on this subject is (like you all said) very generic and not targeted to CoreOS Container Linux deployments. Which is fine, but I was hoping to find a guide on how to get the obvious combination of CoreOS Container Linux and CoreOS Etcd to work together: https://coreos.com/etcd/docs/latest/upgrades/upgrade_3_0.html

So my first thought was to shutdown the EC2 VM using this CloudInit:
```
#cloud-config
coreos:
  etcd2:
    advertise-client-urls: http://$private_ipv4:2379
    initial-advertise-peer-urls: http://$private_ipv4:2380
    name: 'etcd-node-1'
    initial-cluster: 'node-1=http://10.199.16.42:2380,etcd-node-2=http://10.199.32.42:2380etcd-node-3=http://10.199.48.42:2380'
    initial-cluster-state: 'new'
    listen-client-urls: 'http://0.0.0.0:2379'
    listen-peer-urls: http://$private_ipv4:2380
```
and replace it by a new EC2 VM supplied with Ignition userdata:
```
etcd:
  name:                        "{HOSTNAME}"
  advertise_client_urls:       "http://{PRIVATE_IPV4}:2379"
  initial_advertise_peer_urls: "http://{PRIVATE_IPV4}:2380"
  listen_client_urls:          "http://0.0.0.0:2379"
  listen_peer_urls:            "http://{PRIVATE_IPV4}:2380"
  initial-cluster: 'node-1=http://10.199.16.42:2380,etcd-node-2=http://10.199.32.42:2380etcd-node-3=http://10.199.48.42:2380'
  initial_cluster_state:       "existing"
```
Obviously that is not going to work. As the upgrade documentation explains you need to stop the existing v2 process and drop-in replace the v3 binaries. But the approach I just mentioned does something else: it replaces an existing node in the etcd cluster. So using `etcdctl` I needed to remove the old node and add it again with the same endpoint. That is a very different scenario then drop-in replacing the binaries: I see that 😄 

So I went back to my old etcd2 cloudinit based configuration and re-added the node. My v2 cluster was a healthy 3 node cluster yet again.
The next step I took, was my best attempt to drop-in replacing the binaries without actually downloading etcd binaries onto the running CoreOS Container Linux VM. I created by hand the systemd file for the `etcd-member.service` with the configuration I listed above. I stopped the V2 systemd service and started the new etcd-member service. Fully expecting this to work as a drop-in binary replacement. But it failed on the location of the etcd data folder. The old etcdv2 service uses `/var/lib/etcd2` path where the new etcd-member service uses the `/var/lib/etcd` path by default. But that didn't stop me (yet)! I tried to point the etcd-member service to the existing `/var/lib/etcd2` data path. Which resulted in permission problems I couldn't easily fix.

And that left me quite disappointed. In the sense that I expected my setup (a simple 3 node Etcd cluster running on ec2 nodes supplied with userdata configuration on CoreOS' own Container Linux) to be a very common setup which should be easily upgradable to the latest Etcd binaries... Maybe I'm missing something obvious?

Just a sidenote. All Etcd documentation assumes you have `etcdctl` of some kind of v3 version, so that you can make use of `export ETCDCTL_API=3` to access v3 api related commands. But when you run the latest stable version of CoreOS Container Linux you can run a v3 binary using the `etcd-member.service` but `etcdctl` is still of version `2.3.7`?

**Comment by pgburt** [comment]
Appreciate the clarity Arjan! <3

**Comment by radhikapc** [comment]
cc @euank

**Comment by radhikapc** [comment]
it appears to me that we need to create a doc specific to etcd with container linux.

**Comment by euank** [comment]
I had to go through the update from `etcd2.service` -> `etcd-member.service`, and it was definitely a bit painful.

The fact that you can't upgrade from `2.x` to `3.x` but rather must go through `2.x -> 3.0 -> 3.1 -> 3.2` also made it more complicated, in addition to having to fiddle with data directory locations.

> Just a sidenote. All Etcd documentation assumes you have etcdctl of some kind of v3 version, so that you can make use of export ETCDCTL_API=3 to access v3 api related commands. But when you run the latest stable version of CoreOS Container Linux you can run a v3 binary using the etcd-member.service but etcdctl is still of version 2.3.7?

@arjanschaaf at least for that bit, for Container Linux versions starting with v1520 we're including `etcdctl` version 3.x

**Comment by xiang90** [comment]
i am going to close this since it is not strictly etcd related. i am not against it if anyone wants to pick it up again, and put a doc into contrib.
