### ISSUE TITLE
Add Ability to Wait for Peer/Machine Changes

### ISSUE THREAD

**Issue by james-andrewsmith** [coreos/etcd#848]
It would be great to pass wait=true on the /v2/admin/machines endpoint to monitor for new / expired / removed machines.

**Comment by philips** [comment]
With etcd 2.0 machine removal and additions are explicitly made by the systems administrator. This is a change from etcd 0.4 where a machine might be automatically removed from the cluster after some long timeout and replaced by a standby. Because of this change I am going to close this as I don't think there is much utility. Feel free to re-open if you have a use case in-mind.

**Comment by yichengq** [comment]
Based on the discussion OOL, the watch can help on client/proxy rebalance when adding/removing members. Considering the number of client/proxy is big, it is hard for sysadmin to do it manually.

#959 is related to this issue.

We are still unsure about the best way to implement it though:
1. put it into key space, but it pollutes an empty space
2. use another space instead of key space
3. add minimal features to fulfill the requirements of client/proxy

They all have their cons and pros. We will think through it totally when the day comes.

**Comment by xiang90** [comment]
@yichengq After thinking this for a while, I think client keeps on polling every O(10)second level should be good enough. We do not expect the cluster configuration changes a lot and client should handle member failures gracefully (when a member is removed, it is considered as failed)

**Comment by yichengq** [comment]
ack, polling is a solution that is good enough for machine change. And we have provided AutoSync functionality at etcd/client side.

**Comment by xiang90** [comment]
@yichengq Closing since we have an agreement.
