### ISSUE TITLE
"Watch" grpc API not ending when input stream is closed

### ISSUE THREAD

**Issue by hubo1016** [coreos/etcd#8492]
It seems that the "Watch" API do not end when the input stream is closed. I also see that the Go client use cancel() to forcely close the watch stream. Is there a reason for not ending the watch stream? Or if is cancelling the stream API the only correct way to end a watch stream?

**Comment by heyitsanthony** [comment]
@hubo1016 the client will attach multiple watches to a single grpc stream for connection efficiency. Canceling a `Watch` shouldn't take down the entire grpc stream unless there are no other watches on the stream. Calling `Close` on a clientv3 `Watcher` will close all the grpc streams it made, but usually `cancel()` on the `ctx` passed to `client.Watch(ctx, "key")` is enough and preferred. Is there a particular use case you have in mind?

**Comment by hubo1016** [comment]
@heyitsanthony I'm developing a Python binding for etcdv3. I've noticed that even closing the input stream do not end the API call, so there is no "graceful" way to shutdown the API stream. Many other streaming API like Lease.LeaseKeepAlive DO exit when the input stream is closed.

If it is an intended behavior, I will try `cancel()`

**Comment by heyitsanthony** [comment]
@hubo1016 closing the input stream won't close the watch on the server side because there may still be open watches streaming events. This is important for the grpc json gateway because without websockets, it will close the input stream immediately after setting up the first watch, and would never receive events.

Also, in case you haven't seen it, there's already two python bindings for v3:
* https://github.com/kragniz/python-etcd3
* https://github.com/crossbario/txaio-etcd

**Comment by hubo1016** [comment]
@heyitsanthony I'm developing an asyncio Python binding for etcdv3. It is just a simple async wrapper on grpc.io, based on https://github.com/hubo1016/aiogrpc

**Comment by heyitsanthony** [comment]
Questions have been answered; closing.
