### ISSUE TITLE
test: TestV3LeasePrmote flake

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#8740]
--- FAIL: TestV3LeasePrmote (10.51s)
	v3_lease_test.go:76: unexpected lease exists

**Comment by xiang90** [comment]
@jpbetz 

can you help to reproduce this and get it fixed? thank you!

**Comment by jpbetz** [comment]
@xiang90 Digging in now. Is this flaking on Semaphore CI runs?

**Comment by xiang90** [comment]
@jpbetz Yes.

**Comment by xiang90** [comment]
maybe the machine was just slow. but i want to make sure we are not missing anything.

**Comment by jpbetz** [comment]
Thanks.
So far the test logic looks correct. I need to review the lease implementation a bit more closely and then I'll decide what to do.

I hate blindly increasing timeout limits on integration/e2e tests to try to keep them from flaking, so I might first add some more testing logic to probe for how long the lease does take to expire if it doesn't expire when the test expects so we can narrow down if this is a timing issue or not.

**Comment by xiang90** [comment]
> I hate blindly increasing timeout limits on integration/e2e tests to try to keep them from flaking, so I might first add some more testing logic to probe for how long the lease does take to expire if it doesn't expire when the test expects so we can narrow down if this is a timing issue or not.

100% agree.

**Comment by jpbetz** [comment]
As currently written, the test gives 1 second leeway when checking that the lease has expired.

Here are some pass rate numbers from running the test on my dev box with varying leeway on timing.

~0.3% pass rate with 300ms leeway
36% pass rate with 400ms leeway
98.4% pass rate with 500ms leeway

So it's not unreasonable to expect this to fail at a low rate on CI infrastructure a small fraction of the time. I'd expect it to fail at higher rate than on my dev box, since it's a dedicated machine with plenty of resources.

I'll update the test to check repeatedly for the lease to expire for up to 30 seconds, existing immediately with a PASS once the lease expires. This should result in this test running faster on average and be much less likely to flake.

**Comment by xiang90** [comment]
@jpbetz 

> 98.4% pass rate with 500ms leeway

will it approach to 100% if you increase the timeout to say 1.5 seconds? if it is not approach to 100%, i think something goes wrong. i cannot believe a few go routines cannot get scheduled within 1.5s.

**Comment by jpbetz** [comment]
Yes, I hit 100% pass rate at 750ms on my dev box before making the changes. I suspect the 1s timeout for the test was somewhere in the P99 range for pass rates on semaphore.

**Comment by xiang90** [comment]
@jpbetz great. thank you.
