### ISSUE TITLE
etcdserver: Why do the configuration change validation after through consensus

### ISSUE THREAD

**Issue by kr1sten0** [coreos/etcd#8951]
https://github.com/coreos/etcd/blob/b041ce5d514a4b4aaeefbffb008f0c7570a18986/etcdserver/server.go#L1402

Why not do the validation before the consensus?
If something conflicts with current cluster, it can return error response quickly

**Comment by mitake** [comment]
@kr1sten0 checking configuration change before consensus isn't ideal because their execution cannot be linearized e.g. multiple operations can be validated even if one of them makes another invalid. Of course it wouldn't be problematic in a practical manner. For example, the checking required by strict reconfiguration is executed before consensus. BTW this `ValidateConfigurationChange` was introduced this PR https://github.com/coreos/etcd/pull/1623 so I'm not fully sure about the intention ;)

BTW is the quick error response required for your use case @kr1sten0 ?

**Comment by xiang90** [comment]
I am closing this due to low activity. @mitake 's answer is reasonable.
