### ISSUE TITLE
AuthToken needed even in non-https mode in 3.2.16

### ISSUE THREAD

**Issue by sttts** [coreos/etcd#9349]
Compare https://github.com/kubernetes/kubernetes/pull/60299.

Without setting AuthToken in the server config struct, one gets:
```
utils.go:293: Failed to start etcd server error=failed to initialize the etcd server: auth: invalid auth options
```

Is this intentional?

**Comment by mitake** [comment]
@sttts thanks for your report. Probably allowing empty AuthToken would be rationale. How do you think? @xiang90 If it is ok, I'll work on it.

**Comment by gyuho** [comment]
@mitake How about default to `"simple"` in `etcdserver.NewServer`, rather than implementing no-op `TokenProvider` with empty token?

**Comment by mitake** [comment]
@gyuho probably providing a nop auth token provider would be valuable because the stateful nature of simple  token provides complexity and the jwt token requires keys for signing and verifying even if it isn't used. The nop token provider will be useful for deployments where CN based authentication is used.
