### ISSUE TITLE
Issues about 3 nodes etcd cluster 

### ISSUE THREAD

**Issue by itnikita** [coreos/etcd#9376]
centos7.2 64bit ext4 filesystem
uname -an
Linux etcd-host3 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

3 nodes etcd cluter

etcd -version
etcd Version: 3.2.11
Git SHA: 1e1dbb2
Go Version: go1.8.3
Go OS/Arch: linux/amd64

etcd is installed by yum

rpm -qa|grep etcd
etcd-3.2.11-1.el7.x86_64

here is one of node config

cat /etc/etcd/etcd.conf 
#[Member]
ETCD_DATA_DIR="/var/lib/etcd/etcd3.etcd"
ETCD_WAL_DIR="/var/lib/etcd/wal"
ETCD_LISTEN_PEER_URLS="https://192.168.9.183:2380"
ETCD_LISTEN_CLIENT_URLS="https://192.168.9.183:2379,http://127.0.0.1:2379"
ETCD_MAX_SNAPSHOTS="5"
ETCD_MAX_WALS="5"
ETCD_NAME="etcd3"
ETCD_SNAPSHOT_COUNT="10000"
ETCD_HEARTBEAT_INTERVAL="100"
ETCD_ELECTION_TIMEOUT="1000"
#[Clustering]
ETCD_INITIAL_ADVERTISE_PEER_URLS="https://192.168.9.183:2380"
ETCD_ADVERTISE_CLIENT_URLS="https://192.168.9.183:2379"
ETCD_INITIAL_CLUSTER="etcd1=https://192.168.9.181:2380,etcd2=https://192.168.9.182:2380,etcd3=https://192.168.9.183:2380"
ETCD_INITIAL_CLUSTER_TOKEN="etcd-cluster"
ETCD_INITIAL_CLUSTER_STATE="new"
#[Security]
ETCD_CERT_FILE="/etc/etcd/ssl/etcd.pem"
ETCD_KEY_FILE="/etc/etcd/ssl/etcd-key.pem"
ETCD_CLIENT_CERT_AUTH="true"
ETCD_TRUSTED_CA_FILE="/etc/etcd/ssl/etcd-root-ca.pem"
ETCD_PEER_CERT_FILE="/etc/etcd/ssl/etcd.pem"
ETCD_PEER_KEY_FILE="/etc/etcd/ssl/etcd-key.pem"
ETCD_PEER_CLIENT_CERT_AUTH="true"
ETCD_PEER_TRUSTED_CA_FILE="/etc/etcd/ssl/etcd-root-ca.pem"
#[Version]
#ETCD_VERSION="false"
#ETCD_AUTO_COMPACTION_RETENTION="0"
#
#[Profiling]
#ETCD_ENABLE_PPROF="false"
#ETCD_METRICS="basic"
#
#[Auth]
#ETCD_AUTH_TOKEN="simple" 

the cluster seems running good.

etcdctl --cacert=/etc/etcd/ssl/etcd-root-ca.pem --cert=/etc/etcd/ssl/etcd.pem --key=/etc/etcd/ssl/etcd-key.pem --endpoints=https://192.168.9.181:2379,https://192.168.9.182:2379,https://192.168.9.183:2379 endpoint health
https://192.168.9.182:2379 is healthy: successfully committed proposal: took = 3.048946ms
https://192.168.9.183:2379 is healthy: successfully committed proposal: took = 3.771623ms
https://192.168.9.181:2379 is healthy: successfully committed proposal: took = 4.227713ms

Here is my questions.

Q1: what is the cluter version 
logs shows that:

Mar 01 11:29:53 etcd-host3 etcd[7132]: set the initial cluster version to 3.0
Mar 01 11:29:53 etcd-host3 etcd[7132]: enabled capabilities for version 3.0
Mar 01 11:29:53 etcd-host3 etcd[7132]: updated the cluster version from 3.0 to 3.2
Mar 01 11:29:53 etcd-host3 etcd[7132]: enabled capabilities for version 3.2

So why it initial to 3.0 and update to 3.2
can it initial to 3.2 in the first place directly?
what is the different of 3.0 and 3.2?
can I set the cluster version by hand in conf file?

Q2:  Is 127.0.0.1 insecure?
logs shows:
serving insecure client requests on 127.0.0.1:2379, this is strongly discouraged!

how can I void this?

Q3：what does it mean by scheme？
logs says 
Mar 01 12:37:06 etcd-host3 etcd[7279]: dialing to target with scheme: ""
Mar 01 12:37:06 etcd-host3 etcd[7279]: could not get resolver for scheme: ""

Q4:
logs:
simple token is not cryptographically signed
what does the log mean?

In my case, after I install etcd the default conf is that
#ETCD_AUTH_TOKEN="simple"

https://github.com/coreos/etcd/blob/master/Documentation/op-guide/configuration.md
but in this github url , Auth flags is --auth-token
So what is different ETCD_AUTH_TOKEN and --auth-token? Is it the same?
what is the best value when I use ssl https and pem to void the log.

**Comment by hexfusion** [comment]
Hi @itnikita great questions.

> Q1: what is the cluter version
> logs shows that:

> Mar 01 11:29:53 etcd-host3 etcd[7132]: set the initial cluster version to 3.0
>Mar 01 11:29:53 etcd-host3 etcd[7132]: enabled capabilities for version 3.0
>Mar 01 11:29:53 etcd-host3 etcd[7132]: updated the cluster version from 3.0 to 3.2
> Mar 01 11:29:53 etcd-host3 etcd[7132]: enabled capabilities for version 3.2

> So why it initial to 3.0 and update to 3.2

In the case that you have multiple etcd versions in your cluster ie 3.2.16, 3.2.10, 3.3.0 you start with a base of 3.0 and then the cluster  will settle on the lowest common denominator in this case 3.2

> can it initial to 3.2 in the first place directly?

no but this is not an error or problem.

>what is the different of 3.0 and 3.2?

 these are etcd version numbers not sure I understand the question.

>can I set the cluster version by hand in conf file?

not the resulting cluster version this is decided among the members.

>Q2: Is 127.0.0.1 insecure?
logs shows:
serving insecure client requests on 127.0.0.1:2379, this is strongly discouraged!

> how can I void this?

You get this logged because you are not using TLS see https://github.com/coreos/etcd/blob/master/Documentation/op-guide/security.md

> Q3：what does it mean by scheme？
logs says
Mar 01 12:37:06 etcd-host3 etcd[7279]: dialing to target with scheme: ""
Mar 01 12:37:06 etcd-host3 etcd[7279]: could not get resolver for scheme: ""

I agree this is seemingly confusing. But here we are dialing grpc-go without a scheme ie localhost:12345 vs http://localhost:12345 . This is normal and expected.

> Q4:
logs:
simple token is not cryptographically signed
what does the log mean?

Again somewhat cryptic but this is regarding authentication. It is basically telling you that you are not using JWT by default which does cryptographically sign its token. 

> So what is different ETCD_AUTH_TOKEN and --auth-token? Is it the same?

They are the same etcd accepts ENV var or flags to pass arguments.

I hope this answers your questions.

**Comment by hexfusion** [comment]
feel free to ask any additional questions here.
