### ISSUE TITLE
is it possible to get the keys and values in utf-8 encoding instead of base64 in http api?

### ISSUE THREAD

**Issue by spinenkoia** [coreos/etcd#9428]
# is it possible to get the keys and values in utf-8 encoding instead of base64 in http api?

we don't need base64 encoding, we only need the string in utf8, but we have to use it. Is it possible to disable it?

**Comment by socketpair** [comment]
I agree. It would be nice to have special parameter in HTTP-API (like `?nobase64=true`). If that parameter set, etcd should interpret bytes of KEY and VALUE as UTF-8 strings and return them in JSONs. So, etcd must generate HTTP error if key or value is not a valid UTF-8 sequence. etcd must escape symbols according to JSON rules.

Pros:
* usually etcd contains UTF-8 strings, so UTF-8 in JSON is much cleaner
* UTF-8 in JSONs consume less space comparing to base64. Almost the same amount of raw bytes except rare cases when escape needed.
* This way of change is backward-compatible. (but IMHO UTF8-mode should be default)

Cons:
* etcd shuold try to decode keys and values as UTF-8 and also escape. I did not check if it is faster/slower than encoding to base64.

Instead of specifying mode of encoding in URL, we may choose specifying in special key(s) in JSON which values are base64-d and which are not. For example, this way is chosen in LDAP LDIFF format.

**Comment by gyuho** [comment]
Which HTTP API are we talking about? v2 API? Or v3 grpc gateway?

**Comment by spinenkoia** [comment]
v3 grpc gateway

**Comment by hexfusion** [comment]
@spinenkoia, @socketpair Why not use a client that does this work? Can you explain how you are interacting with gRPC gateway and why using one of the clients written for this purpose would not suffice?

https://github.com/coreos/etcd/blob/master/Documentation/integrations.md

**Comment by spinenkoia** [comment]
@hexfusion 
We write our wrapper in python 3 + aiohttp. Ready-made solutions did not suit us for various reasons, such as the architecture of the wrapper or the fact that are used the threads, etc. With gRPC gateway we work through aiohttp.ClientSession using the JSON API. You can of course still wrapped in base64, but why and inconvenient for debugging.

**Comment by hexfusion** [comment]
I guess I don't understand why data conversion would not happen on client side which is both cheap and trivial. If you are writing something in python adding a human readable debug before/after conversion doesn't fit your requirements? I will leave this open for conversation but the complexity of managing multiple data types, not breaking all existing clients and overhead of these conversions by the server don't seem practical to me.

**Comment by socketpair** [comment]
1. Proposed change is backward-compatible.
2. base64 eats more bytes on a wire, and not human-friendly for debugging
3. base64 requires additional memory and CPU in order to use strings in our cases.
4. Proposed change actually REDUCES overhead on the server. I will provide benchmarks later

**Comment by styleex** [comment]
I wrote a simple benchmark comparing serialization of a simple unicode string and serializing the base64 string:

```
package selecta_negotiate_helper

import (
	"encoding/base64"
	"encoding/json"
	"testing"
)

var byteString []byte
var size = 100*1024*1024


func init() {
	unicodeString := make([]rune, size)

	for i := 0; i<size; i++ {
		unicodeString[i] = 'п'
	}

	byteString = []byte(string(unicodeString))
}


func BenchmarkUnicode(b *testing.B) {
	resp, err := json.Marshal(string(byteString))
	if err != nil {
		b.Fatal(err)
	}

	if resp == nil {
		b.Fatal("Cant marshal unicode string")
	}
}


func BenchmarkBase64(b *testing.B)  {
	resp, err := json.Marshal(base64.StdEncoding.EncodeToString(byteString))
	if err != nil {
		b.Fatal(err)
	}

	if resp == nil {
		b.Fatal("Cant marshal base64 string")
	}
}
```

Results: 

```
goos: linux
goarch: amd64

BenchmarkUnicode-8      2000000000               0.09 ns/op
BenchmarkBase64-8       2000000000               0.09 ns/op
```

**Comment by socketpair** [comment]
@gyuho maybe.but https://github.com/grpc-ecosystem/grpc-gateway/search?utf8=%E2%9C%93&q=base64.StdEncoding.Encode&type=

shows that base64-encoding of data that should be passed to user somewhere in another place....

**Comment by hexfusion** [comment]
> shows that base64-encoding of data that should be passed to user somewhere in another place....

yes by client not by server right?

**Comment by socketpair** [comment]
@hexfusion Since both (client and server) may send binary data, they both should use base64 without this patch. My proposition -- is to add API that allows any of them to specify that data it sends should be use directly (not interpreted as base64). In order to implement this one side should send data directly and set some flag. Other side should read this flag and use base64 or not depending on this flag.

Anyway, current implementation of grpc-gateway should have code to encode base64 (for sending to user) and decode (for receiving from user). Does not it ?

**Comment by gyuho** [comment]
I am closing this for now. This is a feature that needs to be supported from upstream gRPC gateway. Please open an issue on gRPC gateway.

**Comment by socketpair** [comment]
@gyuho please point me to the github repository where I should report this feature.

**Comment by gyuho** [comment]
@socketpair Can you open an issue at https://github.com/grpc-ecosystem/grpc-gateway?
