### ISSUE TITLE
Filtering wait notifications

### ISSUE THREAD

**Issue by asiragusa** [coreos/etcd#952]
It would be nice to be able to filter the wait notifications. In my use case I set a key with a ttl and I update it every n seconds. Being able to filter out the update notifications would heavily reduce the number of notifications I get

**Comment by abourget** [comment]
me too, let's ignore (or add a flag to ignore) TTL changes for watchers.

**Comment by abourget** [comment]
I really assumed this was built in.. I'm designing a simple discovery service with TTLs and we currently need to do some convoluted stuff to have this work.. and it's very imperfect because of the lack of this feature.

**Comment by gtoff** [comment]
+1 for wanting this

**Comment by xiang90** [comment]
@nikfoundas @abourget @gtoff @asiragusa @ashun 

v3 watch will ignore TTL updates. But for other kinds of filtering, I think a better way is a client-side filter. Any opinion?

**Comment by ashun** [comment]
Hi Xiang Li,

That's a long-waited feature, but it's better a server-side filter.

That's because:
1. all the existed etcd clients written in different programming language
will have to implement this feature.
2. etcd server has to push every TTL update to all clients waiting on the
key, that will cause server load and network load increases.

So on my opinion, server-side implements is a better idea.

Best regards

**Comment by xiang90** [comment]
> 1. all the existed etcd clients written in different programming language
will have to implement this feature.

If the client can do that, we would suggest the client to do it. We cannot anticipant all kinds of filtering anyway. We want to keep etcd as simple as possible at the moment. We might add filter into etcd server when we have strong confidence.

> 2. etcd server has to push every TTL update to all clients waiting on the
key, that will cause server load and network load increases.

We have decided not to send ttl update notification to client in v3 API.

**Comment by abourget** [comment]
I agree with this pattern. Not sending notifications solves the issue at hand. Implementing filters client-side for other stuff makes sense.

**Comment by gtoff** [comment]
agreed

**Comment by cchamplin** [comment]
I've put together an implementation for this for 2.x. More details here https://github.com/coreos/etcd/issues/1229#issuecomment-142124136

**Comment by xiang90** [comment]
@cchamplin I think this issue is settled down. At server side, we will filter out TTL updates in v3. We will leave other kinds of filtering to client side. 

For v2, we do not have a plan. But if you want to contribute, welcome to do that: auto filter out TTL updates with an additional flag; leave other kinds of filtering at client-side.
