### ISSUE TITLE
Leading spaces in ETCDCTL_ENDPOINTS confuse etcdctl

### ISSUE THREAD

**Issue by omkensey** [coreos/etcd#9583]
If I set the ETCDCTL_ENDPOINTS environment variable to a value with a leading space, etcdctl cannot contact the endpoint:

```
$ export ETCDCTL_ENDPOINTS="http://localhost:20001"
$ etcdctl member list
ce829ded45252089: name=etcd-1 peerURLs=http://127.0.0.1:10001 clientURLs=http://127.0.0.1:20001 isLeader=true
$ export ETCDCTL_API=3
$ etcdctl member list
ce829ded45252089, started, etcd-1, http://127.0.0.1:10001, http://127.0.0.1:20001
$ unset ETCDCTL_API
$ export ETCDCTL_ENDPOINTS=" http://localhost:20001"
$ etcdctl member list
parse  http://localhost:20001: first path segment in URL cannot contain colon
$ export ETCDCTL_API=3
$ etcdctl member list
Error: dial tcp: address  http://localhost:20001: too many colons in address
```

**Comment by hexfusion** [comment]
> Error: dial tcp: address  http://localhost:20001: too many colons in address

@omkensey thanks for the report, this looks like an error from url.Parse or simular. Are you interested in taking a further look at the issue? Same thing happens if you were to do this. 

`etcdctl --endpoints=" http://127.0.0.1:2379" member list`

or this 

https://play.golang.org/p/2K5qB3xWoga

**Comment by omkensey** [comment]
Sure, I can help out testing further cases or fixes or whatever.

**Comment by gyuho** [comment]
@omkensey We can just trim the extra whitespace characters. Would be great if you can contribute.

**Comment by omkensey** [comment]
I can give it a shot.  I haven't written much Go before but it sounds like a pretty simple change.

**Comment by gyuho** [comment]
@omkensey Thanks! You can start from here https://github.com/coreos/etcd/blob/master/etcdctl/ctlv3/command/global.go#L135.

**Comment by vimalk78** [comment]
@gyuho , i have looked into the issue and i see two options.

option 1 : trim the value returned by `endpointsFromCmd(cmd)`
https://github.com/coreos/etcd/blob/master/etcdctl/ctlv3/command/global.go#L139

option 2: there is an "ip slice" flag in `vendor/github.com/spf13/pflag/` which can trim the spaces
https://github.com/coreos/etcd/blob/master/vendor/github.com/spf13/pflag/ip_slice.go#L39
we can define the `"endpoints"` flag as an `ip_slice` instead of `string_slice`, and construct the `[]string` required by `endpointsFromCmd`

what do you suggest? i will send PR accordingly.
