### ISSUE TITLE
[Documentation]  Specify Location of Snapshot files when using wals-dir

### ISSUE THREAD

**Issue by bearrito** [coreos/etcd#9781]
It isn't clear from the current documentation if snapshot files will land in the wals-dir (if set) or in the data-dir

https://coreos.com/etcd/docs/3.2.17/op-guide/configuration.html#member-flags

**Comment by hexfusion** [comment]
> It isn't clear from the current documentation if snapshot files will land in the wals-dir (if set) or in the data-dir

"Path to the **dedicated** wal directory. If this flag is set, etcd will write the WAL files to the walDir rather than the dataDir. "

hi @bearrito the documentation doesn't mention snap dir directly here as it is the documentation for the wal-dir flag. It does say that it is a dedicated directory for the WAL file which makes sense to me.

But here we outline more technical details about the snapshot process. https://github.com/coreos/etcd/blob/master/Documentation/op-guide/maintenance.md#raft-log-retention.

Are you looking to append the docs or are you just making an observation?

**Comment by bearrito** [comment]
I assumed as much, but the issue was not clear to me as snapshot files and wal files seem to differ in some important ways. 

We are hitting what looks to be the 500 Node problem in terms of etcd io. My use case is that I wanted to write snapshots to persistent but slower storage while allowing the wal files themselves to be stored on the faster but ephemeral local storage.  Similar to the approach https://blog.openai.com/scaling-kubernetes-to-2500-nodes/ but with safe storage of snapshots.

**Comment by bearrito** [comment]
I believe this can be closed as resolved.
