### ISSUE TITLE
minor readme terminology change

### ISSUE THREAD

**Issue by maninalift** [coreos/etcd#9798]
Apologies if this just seems like pedantry.

Your readme confused me briefly because it talked about a "bi-weekly" (which means twice a week) meeting when I think it should say "fortnightly".

**Comment by hexfusion** [comment]
> Your readme confused me briefly because it talked about a "bi-weekly" (which means twice a week) meeting when I think it should say "fortnightly".

Hi @maninalift, welcome!  I am not sure if using fortnightly adds much clarity though as it is not a commonly used word in the US. Biweekly does technically mean every other week _or_ twice a week, since we also explicitly set Tuesday as the day for the meeting this eliminates that ambiguity.

https://en.wikipedia.org/wiki/Biweekly

Going to close this, but I appreciate taking the time to make the issue. If we here of additional confusion like this we can revisit.
