### ISSUE TITLE
etcd community proposes potential CNCF adoption

### ISSUE THREAD

**Issue by hexfusion** [coreos/etcd#9964]
This issue is to make the etcd community aware of the pending TOC proposal to CNCF about etcd and also to track its progress.

ref: https://github.com/cncf/toc/issues/136

**Comment by purpleidea** [comment]
I'm against moving things into foundations like this. It's a 501(c)(6) not a 501(c)(3) so we need additional written assurances to prevent complete corporate control and "pay to play" direction so that smaller parties have an influence too.

In particular, if contributing to etcd in the future would require signing a CLA, I would most likely find it difficult to send any future patches.

I'm only contributor #30 ( https://github.com/coreos/etcd/graphs/contributors ) but I'd like to think I'm involved a lot in the project, and have a lot of future work that I'd plan to contribute, as well as do a good deal of testing.

Thanks

**Comment by gyuho** [comment]
@purpleidea Thanks for your feedback. Let's move this discussion to https://github.com/cncf/toc/issues/136.
