### ISSUE TITLE
`etcdctl snapshot save` should restrict file permissions so only the user can read the file

### ISSUE THREAD

**Issue by dlipovetsky** [coreos/etcd#9976]
I noticed this, and I couldn't think of a reason why the snapshot, by default, should be readable by anyone but the user.
```
$  etcdctl version
etcdctl version: 3.3.3
API version: 3.3
$ whoami
root
$ etcdctl snapshot save ~/etcd.snapshot
Snapshot saved at /root/etcd.snapshot
$ ls -al ~/etcd.snapshot
-rw-r--r--. 1 root root 3473440 Aug  2 01:42 /root/etcd.snapshot
```

**Comment by hexfusion** [comment]
@dlipovetsky, so instead of 0644 `-rw-r--r--` maybe 0600 `-rw-------` would be a safer permission given the possible sensitive nature of the data. But if the directory it is stored in has the correct permissions then the file is not actually readable by another user. This would be the case of the /root directory in most cases mine is 0710 `drwx--x---`.

But etcdctl can't be responsible for it's surroundings so I think it's a good idea in general, are you interested in exploring this? I can't think of any reason to not restrict the perms honestly.

**Comment by dlipovetsky** [comment]
@hexfusion Agree 100%. Thanks for taking a look!

I'll take a stab at a PR.
